apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - agent-configmap.yaml
  - gateway-configmap.yaml
  - daemonset.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
