apiVersion: v1
kind: Secret
metadata:
    name: argo-workflows-sso
    namespace: backup-system
stringData:
    client-id: ENC[AES256_GCM,data:8fkiVk9xVfn2qVle9Eg=,iv:xp24LY112b+J2KTGbQs9RBPPLceJ/hFVP+JStnj7v1o=,tag:FxUnYy9e/FMs1v2NVk3ZuQ==,type:str]
    client-secret: ENC[AES256_GCM,data:bxdJ4uULcR2ndbBwM90z6kABzvUTQTVf4dTMonYYsAVyj2kNWLr7Gr6kGWO4DsZBqAzv1/x/hVMsOOG2qiQjYw==,iv:E9eRZlMVfiH0ZsIjl6rF9WSHLsS+yRLT+EhwpJS8ULw=,tag:lgFixO5IagqgetSrmfPxRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV2FscG0xUEFlVncwVkNr
            YzlsUXhlR3Y5bk0wRHRsd2pQOGpFaDRDeVVVClM5NlZwY2dRejVkS3hDYTdwa1dY
            dk5rdlNDaisvSWFIeVpHaXFNVTZhSGsKLS0tIEc2dW92eTNETjczNDkwaHJLZGFi
            ZitWclNERkVCNU1KMEJIa0hybG1UdmsKkpIpiUg+ZTnFubgxE68VsJLMzVJwsVHc
            vcg7/Jk+ZSdEYSwOBoe+MaEJLUrCs7z8NkkCIa8581EYmU15ZcBhjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T09:05:26Z"
    mac: ENC[AES256_GCM,data:Rspy8rQcu+9MzPefgdt6xo+3yN/g2Jezdh41JeGLwCvQX0a1UIVZVsolW/pCOHtgDg45bBmQCtp2aWGJVx2DTVz9SZ9HHg5+KgYqcOh4Ld5osv+BYPeTDlRKYY6ktXsACvdYSIvDmeOfZOqCowSSdyUYYX8Yl2F3WV5hmjp+hbc=,iv:27R3MF41wwUN0qr2zTEqWOMS+D6rS+AKHhEb5hmBEac=,tag:hyASpEHaMQZ90H/4yRHAgw==,type:str]
    version: 3.13.3
