apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - argo-workflows.yaml
  - restic-secret.yaml
  - rbac.yaml
  - workflow-templates/volume-clone.yaml
  - recovery-policy.yaml
  - workflow-templates/restic-dataset.yaml
  - workflow-templates/sqlite-dataset.yaml
  - workflow-templates/recovery-point.yaml
  - cronworkflows.yaml
