apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - argo-workflows.yaml
  - argo-workflows-sso-secret.yaml
  - restic-secret.yaml
  - recovery-aws-promoter.yaml
  - recovery-aws-retention.yaml
  - rbac.yaml
  - rbac-cnpg.yaml
  - rbac-reconciler.yaml
