apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - securitypolicy-referencegrant.yaml
  - cilium-policy.yaml
  - postgres-cluster.yaml
  - objectstore.yaml
  - archive-netpol.yaml
