# Encrypt with SOPS before committing
# Get values from: terraform output -json velero_access_key_id velero_secret_access_key
apiVersion: v1
kind: Secret
metadata:
    name: velero-aws-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:TBjaEsDmgRJIsmKvTgHT/uhMs8SAuGnjneX2Yy1jT4qyzbAHHRQo38Q1L+UWvG8nImuWrX68cqElA5gHetPKU9ZDahviye2wDVgChmjwjHXjpYDpkFSGfVlFD1npMKdwl/Ul8rp36/z052aLvkVqQg==,iv:F4THv82Xrv47OrOF32HPwYR4QD65LTuNdgOjFkZi5cw=,tag:2PtW8ekZHsYCbl/7meXjoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadTVXbGZnZ0I5M3hCYlpS
            V1hSSEVsVElzaWlqMFNmS3hLMmhUMlFWc2tFClNBVFg0U1hBcXZjbS95UzlWMFNk
            Z2I4c3FrOVJEZEJwVWU2WVZhcUZsU1kKLS0tIEtlK3NWTUc3QkRiU0NDRTcwSXp1
            MWR4RnorM3p3TTdlazA2bHdidTJyem8Kd5jS1m4OKTDZYl6V5Po0wOge/l83rj67
            e5piZ1Wq+BfMhAfKjjXbXmnLxUQcppqeyTSpde7TIj6eJbT5+tJBAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T18:57:19Z"
    mac: ENC[AES256_GCM,data:RbGL1v8un1NzU2PpL1aat0qB4b+kHrlUGq16f8enoFhBNXR6IXOxSV9qnwumCbYCzFczBocAqTGjuQsOEanvzJfh9uACXG735hiqKOno7KsL/2yMUbh4K+H00qF+RfdEXsocWGsWkiWX1+3aIVlwgLVyL/27SfrH3CPI2LVsYUg=,iv:+P0rcYRv1mU64uuPWs1uVy9815ibe8H/c5so/KVsX2E=,tag:g6rIekrsq5XtueN8tq2JqQ==,type:str]
    version: 3.13.3
