# Encrypt with SOPS before committing:
#   sops --encrypt --in-place seaweedfs-secret.yaml
#
# The 'cloud' key uses AWS CLI credential format expected by velero-plugin-for-aws.
apiVersion: v1
kind: Secret
metadata:
    name: velero-seaweedfs-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:o/zt9+4TIMQKHWWrXF5aYdpLSYi5rB35XonYVqdRQV/hrK265n5zK/OFrwtp51qpO/LZTHRzfbCAeSjUANXsjKLfl77Zv/Am,iv:EU9/xL9x9mp1slfN1Vmo35gCBi8X8sLqq0YyeCE7Fho=,tag:lrhmIZTj6WcYTrGVvsK4wg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZWJFSDRxc0ZlRGxHVkxG
            Y3o4TlRyVVF4dDIzOURUMTNic1ZHcVRIR1NrCk1vNjh1dHJSRUNFd2ZyTVJkNUxq
            NElCOUQreFdheUJBSTRnZUl5UkJXVzAKLS0tIE84MmVYUk1vQzJkSDFWbWlCQi9B
            cGpQYWd5S1g5S0NCU1d1bWp6dU9tV3MK91DJID7hwXAy3QpazkvRFpnm2zG3iIQH
            mR58HV2AfpnjZD4JrYf9TE86pijmVWCMDxl//fE8JdarurL7rYFRTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T20:31:46Z"
    mac: ENC[AES256_GCM,data:BZ2JKhBMSrXsU2p66GO3Ub5qf1QVScmAhvx2U/fy1MVus8+bUJ+3sjTbPRNFNtvzq60qrX+DSPffSyO2MDEmPsOFBlMcBLyhFDTzRvuglk3lxrsR+Z4Dc76xS6x6Lz+2c0GrGm4z5tpKsEadR49m/zBNFVSRxUTs+etdKvYFnv4=,iv:3eQLeoZRZzMYpqvQF8u3KIpof9zH1k5u5fyg0DVdW6E=,tag:QP9abuZ02+87cqUA2v1v3g==,type:str]
    version: 3.13.3
