---
# Source: EdgeX/templates/edgex-consul/edgex-consul-service.yaml
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-consul
  name: edgex-core-consul
spec:
  ports:
  - name: "http"
    port: 8500
  selector:
    org.edgexfoundry.service: edgex-core-consul
  type: ClusterIP
