---
# Source: EdgeX/templates/edgex-redis/edgex-redis-service.yaml
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-redis
  name: edgex-redis
spec:
  ports:
    - name: "http"
      port: 6379
  selector:
    org.edgexfoundry.service: edgex-redis
  type: ClusterIP
status:
  loadBalancer: {}
