apiVersion: v1
kind: Secret
metadata:
    name: keycloak-argo-workflows-oidc
    namespace: keycloak
stringData:
    argo-workflows-client-secret: ENC[AES256_GCM,data:4wFX42h/ysphU0BtyVkKiRI0N0iFdUKSkGMojIPs3Ny9Iegu84mqDcI/Mh33IpaA+q0NrKeXcw6pgxgpvfSIgQ==,iv:qdZgh9I17ZfHTDhY+d3y9zzxJJTws6+qSyEXcNLEhwA=,tag:jM7aNtMCZrZ/+BaSnCBEhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNk5hQW1zOWJxdmhma3lS
            c0ZYbkU0anQrK0ltVE94VUx5dmlYcDdYVjFFCkYvU29tTlFUTlBza0NzMmdaSjM5
            ZFJabkZ5L25hQ2RFNU4yWWJFRGJySzQKLS0tIFNvZDRjOTJiNjN2dVBQNDFxQzF0
            a0dPbnBrUGcya0ZCaWNZZkQ2eVNML2sKinnquCSuu1HMezpNtD3+x9ZgDLjnin2N
            jWkL5xPZfCPt9zpac80oczgWL8BRFadugwVowFN83TZjGsp/yVo3eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T09:05:10Z"
    mac: ENC[AES256_GCM,data:jpZoGDhz+EuyhVYRb7cRe58J8WDmvsMxHhRyxQg7FQFVOJIvAi9DnLGV3/DPhKVyvZXx6l5vt0bfxz7iwiYrgJCMFORK2Z5D3ZnokBwEaNQUddY8FrVb+zZ1fyWnPIZTiBrCYRt6KuRPeY+V2vFAznggBp/an9e23mLgaZGhN7Q=,iv:U6gBY6tn3xl0vs4xHEylKjudBrJvUFN/yMw9DVTbzFY=,tag:lXuP8cAIfiENZqspvnb9cg==,type:str]
    version: 3.13.3
