apiVersion: v1
kind: Secret
metadata:
    name: keycloak-hubble-oidc
    namespace: keycloak
stringData:
    hubble-client-secret: ENC[AES256_GCM,data:zOpA2GbJnu7IKDdfKE71oy4zpT6bh3sDtZALy9maAavIMRHD8Tm3cQ/Awg==,iv:4wA+hYLM0X1t4D/gb1DPOg86lAJRju4A9Gw3N9xA2+w=,tag:Gatr8cCK57YNPgWhOC8/FA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S2N2ZmE3ek4yWnQ1c3FH
            RkpjNXFVbzJHdldHckFoOEVtbXg0cGV0dW40CmlhNnR2clpwWWhBNFN4ZTdIOGJB
            RVVJZzBYMFJFeXBxZWtGTS85TE13Q0UKLS0tIDBVRUNIbHFYbmRKTlhBRlRUV3lN
            QW0wb2dETkx2VlBySHpkdGdxY0hUT3cKmj4svcAIEShPtRXOunQVAbc7xX8eHPGx
            7PPkJvJe9eWozvhPH58FVtK4h03XBWLa12i6kY/1hu7eT6P9P3XWrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T20:27:36Z"
    mac: ENC[AES256_GCM,data:jfaAHull7xy03+v2Sx2IFFr9jUogKBgT38V5qJk7PhtPWdrKQpM0QZaTeDK3blEwrYV37aXijy3qiDQWdABlnroBQiwnJLxtmBJaB/Rlch/eIKxy0ylk/pMfLZ1l/nhVrydIzWftgomtQZtjhYYZqZxXrkdO9UK3U5DPi/PKcpk=,iv:Ao12IOlGOoVRpy6jNxtzpKoXw3OJzBCePXgTS7qMZaI=,tag:qy3KnvnjEg/n+K/A8rZwmg==,type:str]
    version: 3.13.3
