apiVersion: v1
kind: Secret
metadata:
    name: keycloak-immich-oidc
    namespace: keycloak
stringData:
    immich-client-secret: ENC[AES256_GCM,data:71s9xXqoJE9ccxQT9+JmlEMLnfLBw+4KL0ImGorPQJtpFKOg2voRdT85dw==,iv:CSzlcTW7CFOOjnw+9tADyWsYG9Hu3TUAdPwbjAMxXfU=,tag:9GBj24Pw+XeRJebND5TiUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c2x0WmkxNHBRYmV5K3RI
            QW9idjR0dWt4ZG8vMjZnZHNNWTY1TkNCRlJvClFrQTdVK1QyTHk3SHNIbFhWbGQ5
            QklxS1orWHFxMitlQytKZFFJakNUUTAKLS0tIGxhM242VE9sZkRNMXVBQ3NLQXk3
            MVdUWUxTTFpmQ2taRXhNMk1KdVZSSW8KRWzNWljEDGseKy60lJgHVu4O8AfGA/kg
            SQLWIhMC5tah98hqfF6RuyBDyxfKkTA4rAUd75GVPuNqHmn5h3MS8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T06:30:01Z"
    mac: ENC[AES256_GCM,data:7I4htV16ejdDHpkIBRI0PWyaCaLuB1N5dwTt9FASJAa80KadTD/SiP3N9aAM/8jfiAPcUA07KDVjL7Mx09kODP7UrPSnE8CYt3HIxphNFdIr8apAIRuB7mcrvJZ9ya4ludcMOfJo33VtQe/ZIQqPxX+kCm4TgXWz3R42BSqJTCM=,iv:sf1Ik0uAujkFk5LcBaAQsVWPW1RElSQjhPUf2GWiiPg=,tag:+hqq5aOsnGhd2yJBqUzSmg==,type:str]
    version: 3.13.3
