apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-user
    namespace: keycloak
stringData:
    password: ENC[AES256_GCM,data:cUlWGXe+88fLUS75ROkOEbib+QYZxX+3kc5L5TeccTo=,iv:C/asTSgq11qf2lpqZ7bEY/e4U/2M2Bs0yfCNhS39/7Q=,tag:6pbEjALV2LRPCvMwQ6vm2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeUVPcWRENUNyR3Z3TWJH
            ZUFJZmtwVVh4QjZLOVVQOGxBZmVlTlBmS1RnCmt5VEozbnhaUURQNDZVWVl0TDYy
            OWlraStiU1ErMkkxSHUwem42RTJqMjAKLS0tIHVsMDU0ZVlwOUxsVU95cTg2Sk8r
            MmU1eWdRYlRTZ25ib1E2NE5pTGF2YncK4UYHb4v3DT66zNIrnftxpLtRevAQEprd
            SavYKdeKlPzFxKP3PJ4KUqSNcUixg9zTUWRmDwnee35k+3/pzxYAbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T21:46:21Z"
    mac: ENC[AES256_GCM,data:eL9Az0o/1yxMYuv/2BggDVFh+hphiRnM6bt8SXrRzQ24IPbBqZUBeuH1Cxp3iGbOb/RInMP4HHi2dNdabsVT8zq8rvFKncuhzy1liuNor0xTur/1xDvtAXzNPNvdWAK3c0yHKw5z4eUFcvbx/MhScbQckxpOPVb0ucwy45yNlQI=,iv:UyBsKCfvC6UMZoqp9QHrAJyuN8Dzu1EImlsq7dO1WhE=,tag:STJet+Q1Xbd9/DaKzwPZgQ==,type:str]
    version: 3.13.3
