apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: keycloak
stringData:
    admin-password: ENC[AES256_GCM,data:aXfncCSdfNWrzlg9YjQrzbKcv0zaTqrTHeb3Ac03ZAo=,iv:1VBnmMTZmYu5jOAICL0Eem9YMrtTyy+5wCwXRKz+te0=,tag:JRp+3sV3E/o6AdW73zcROw==,type:str]
    grafana-client-secret: ENC[AES256_GCM,data:ZK1f+hDchcrV4Ho9O4f/AJ0O7m7TeoYk7M/ugi5H0cE=,iv:t7hUc64PBI5UmfVHe0JyjxyS1iJ1az92MfXhU/9yiGs=,tag:Y3JtMF4/H7+DDpSkZ9RJnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZmtJOHl0V01PTW02aFVJ
            YURRVk5YSktIbHRRdlRWVGxoQ2wxSm5yRm1BCnpyV3RObVUycGlWUVFnVUk4RzhM
            ZTBJWHpBVm9yTFlYWmY1MzVxbHdGV3MKLS0tIEV3NXNhUUZySEthQzUvTjR6VnA2
            M0pIem5IMDFnVXp4S1d1MHQrYTRYTjAKMPFmU6U5UBcQgpkFDbyk7xtY2LAEfVR7
            lT7mRohdW0czptwYRV1N5u3Fd/ANstqbqFUQEcOSkRotvP9of4UVIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T13:35:14Z"
    mac: ENC[AES256_GCM,data:f72A3e3tKqCP81s7UwwHOlDcanyWBakZOlNy+8E0wHgZpKLmlfXYrtixLch/W8214lmbX+rf1hmXGGdKWUn/tV7TkRKTfmSwgzeB14xS099+hicCFZgsh9PU05z3ZKe+tez0/AMis3c1VyTx/TW6vSoxMFkY/5BN9V6vo5ZEx74=,iv:BLZ/2WX8j5WEE2CHRIGEJkS0ugh6LfUp3OIsiu0k4sI=,tag:PHlcrESRPE4Qomjbxmu3Mg==,type:str]
    version: 3.13.3
