apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: keycloak
stringData:
    admin-password: ENC[AES256_GCM,data:aXfncCSdfNWrzlg9YjQrzbKcv0zaTqrTHeb3Ac03ZAo=,iv:1VBnmMTZmYu5jOAICL0Eem9YMrtTyy+5wCwXRKz+te0=,tag:JRp+3sV3E/o6AdW73zcROw==,type:str]
    postgres-password: ENC[AES256_GCM,data:a28lTZe1H8RH9uvkTCVHODQqT2vuoqSFzJYgcbZHZ6c=,iv:fANdosexHxdom/m9m4xGJNrQEE+U9gGiRN9agSXE+kQ=,tag:DvSn7tyb4eyF64fEhPl78Q==,type:str]
    postgres-admin-password: ENC[AES256_GCM,data:8EenBN9I4ySH7kew8oMx1xLolhJLNHHhXg/B6/prVsw=,iv:zDLXn/jFrJ/5zXj/e0rAvgmPEAkHxLIrb62oeukAoPc=,tag:MxOzvgKkQhbQUiMWkgXWrQ==,type:str]
    grafana-client-secret: ENC[AES256_GCM,data:ZK1f+hDchcrV4Ho9O4f/AJ0O7m7TeoYk7M/ugi5H0cE=,iv:t7hUc64PBI5UmfVHe0JyjxyS1iJ1az92MfXhU/9yiGs=,tag:Y3JtMF4/H7+DDpSkZ9RJnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZmtJOHl0V01PTW02aFVJ
            YURRVk5YSktIbHRRdlRWVGxoQ2wxSm5yRm1BCnpyV3RObVUycGlWUVFnVUk4RzhM
            ZTBJWHpBVm9yTFlYWmY1MzVxbHdGV3MKLS0tIEV3NXNhUUZySEthQzUvTjR6VnA2
            M0pIem5IMDFnVXp4S1d1MHQrYTRYTjAKMPFmU6U5UBcQgpkFDbyk7xtY2LAEfVR7
            lT7mRohdW0czptwYRV1N5u3Fd/ANstqbqFUQEcOSkRotvP9of4UVIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T20:20:49Z"
    mac: ENC[AES256_GCM,data:enzS28OdyHzksN45NUPJynbGA0nylgxZAmjypBZG/kZzIozWLG6FQLdRlZUmme3B3rwc6jS+G4tLEQAb3TR/MBgUKSFo77yFjo0pFrfdPccwSzkw4MnhFqvJfeZ8+kbj/+qpKN/aAEbyYrmOB+5KTntbxP/z7i7LKgSL/MK2eTs=,iv:+kg5JgWshuJOLPZx25zdL+zH7vQprRe0yK7L3RGI1+g=,tag:FxHFckMz3PosJhThWrsBKg==,type:str]
    version: 3.13.3
