apiVersion: v1
kind: Secret
metadata:
    name: keycloak-kubeopencode-oidc
    namespace: keycloak
stringData:
    kubeopencode-client-secret: ENC[AES256_GCM,data:135+mkDGTJLlMqQa6iVuX7ko7PzYcNY8O2F6Hx95Oy2YC2yRCYa3JdoXZg==,iv:7q54vKFvqy0CO3eyCh3zeXDmwd2ZGW7jFyJGUVN3uK8=,tag:wpbHBJ+vbhibEL3eiJxS5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMlpORE1XNkM3VC9uTnBt
            NGVoemZLOWp6cmlMNTNRWXlxOWxOR0wyYW1VClhDOFRJdGkwdENMbjRsdjAvYkRD
            bERnamlmSVgzdVpWYkRjYXE2NEMzeGsKLS0tIGdCaUVEZ1BkZU9UVkpLb1UzK1RN
            MkdtOCtFdjErdno1Y1pyaFdGb2pDVGMKI8NesVcWvgTcD0KUeTSaCuW3tKy2IkWL
            HwW1ghYPNHUNbyHU3s+PsqkvMIlIdNsMrRSlHzFYvEVA6eEj6yT+gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T20:27:37Z"
    mac: ENC[AES256_GCM,data:26r3fa2D1dF+gSDOgiiHADWwGtNSRDz/8Xs36U7gHAttWa0YVFeObSAB+LVqo50XLSNi1+VxskKBj9e9czy9QBukE2rySNUhetSUKC2zFLVRZNiM1lfd71sYBd+fuvATs5XVk430cu38eQQOUg0wO0Lhc+uZnHFU89IVUz47O1A=,iv:/2uDUVVDmqsvvTYaq0XCQ55TdtkU7L0EHwCEpqhnn7A=,tag:WZEBaWa5YnEuiP+mSaUXsw==,type:str]
    version: 3.13.3
