apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql.yaml
  - deployment.yaml
  - realm-configmap.yaml
  - keycloak-secret.yaml
  - keycloak-admin-user-secret.yaml
  - setup-job.yaml
  - cilium-policy.yaml
