apiVersion: v1
kind: Secret
metadata:
    name: keycloak-paperless-oidc
    namespace: keycloak
stringData:
    paperless-client-secret: ENC[AES256_GCM,data:yAuHctzKerANoURXO1cKp4cZ55KARenfRWM+QrfCgyE=,iv:UnKiNw6W+tk0r0hKhEWDJhlgrbSWVfJT1XNhDf2kSeo=,tag:BO6s6QgmRmKu/FFFPUUoxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OWhGU3JkMkNIT05hWFVm
            TjZnNmZrMCt2Q1B2SWxKeUZKTm9IZHYxMVhBCnN1Y21MdFRSc2lUMVh3cjlQTHpI
            Vk1Qd0xEOUJrVjYzMXhheENVUlBhTDQKLS0tIHlQZHlZclNBdFo3d2dZOCt6aG9t
            NFN6ZzFmMmRTNlNpbjFTcHVjVUdiN28K3pWddgQmmNnFh7GqNBvNM56G0wyiqfgU
            DJXIYyeRzLqf+5wnKQU5KtHidLdoVJo6R6bSENdg6R/2b/CsRCCi+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T07:29:06Z"
    mac: ENC[AES256_GCM,data:zk9STAynytq8r+1TZTA4Kfm4jMjlOL9dr5K5hxqiseCqXnZ4gN4njwsErup7FUJXYcNOwgY+JEFREDa6XgcZ4BdVM2FkpDHt5Etd6U5kbT2qgQVYEat5swxlnV3806WDvNlmT6ikpmfiJBVrqoscT8fyByFrBQh+Qv7KodQbhCc=,iv:zhiVeE/Tt4ajmAwRuZqk4XzeDNKf73WwP8eF2Mnm4ok=,tag:QaCN58TPNYS9zDycIqXfPw==,type:str]
    version: 3.13.3
