apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: keycloak
data:
  homelab.json: |
    {
      "realm": "homelab",
      "enabled": true,
      "displayName": "Homelab",
      "sslRequired": "external",
      "bruteForceProtected": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "ssoSessionIdleTimeout": 86400,
      "ssoSessionMaxLifespan": 604800,
      "accessTokenLifespan": 300,
      "clients": [
        {
          "clientId": "grafana",
          "enabled": true,
          "name": "Grafana",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "authorizationServicesEnabled": false,
          "attributes": {
            "pkce.code.challenge.method": "S256"
          },
          "secret": "${GRAFANA_CLIENT_SECRET}",
          "redirectUris": [
            "https://grafana.homelab.data-harness.org/*"
          ],
          "webOrigins": [
            "https://grafana.homelab.data-harness.org"
          ],
          "optionalClientScopes": [
            "groups"
          ]
        },
        {
          "clientId": "paperless",
          "enabled": true,
          "name": "Paperless-ngx",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "authorizationServicesEnabled": false,
          "secret": "${PAPERLESS_CLIENT_SECRET}",
          "redirectUris": [
            "https://paperless.homelab.data-harness.org/accounts/oidc/keycloak/login/callback/"
          ],
          "webOrigins": [
            "https://paperless.homelab.data-harness.org"
          ],
          "optionalClientScopes": [
            "groups"
          ]
        }
      ],
      "clientScopes": [
        {
          "name": "groups",
          "protocol": "openid-connect",
          "attributes": {
            "include.in.token.scope": "true",
            "display.on.consent.screen": "false"
          },
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ],
      "groups": [
        {
          "name": "admin",
          "path": "/admin"
        }
      ]
    }
