apiVersion: v1
kind: Secret
metadata:
    name: keycloak-schenkmatch-oidc
    namespace: keycloak
stringData:
    schenkmatch-client-secret: ENC[AES256_GCM,data:ElUgMqeJRSQuutGDxZ6ANn0Mxw7Z5N39nwC4BSyYL2+gn9o2foyvNahKWg==,iv:X2NkQ25OQDvDFy2MUUtS+W+LjhMJO+vaJpo4q5RwW1U=,tag:78SWvDpWfwRhOk57Qpw1HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RjkyY0ZHd3dQbVVlNVVY
            N1hXUTlTZzZCOTJKMDVqNitFeEZOclEwU3dNCk5HaE9PZ0NxeEgrUWJTWWJqcDht
            bk0vL25ZT21TUk16Ui9CVlNpcnpVK00KLS0tIGdzL0MzK2ZHRzgyWjBtcE9yVUx0
            eDdPaWRWSW1CaUg5QkQySFRMNTVUY2cKRXeaG9S2P3Xu7I0UDYWwCswj91uiQ5+n
            NXxEjTTDONpzN508Znft0z2InWG/SoizjnyAIQWwCZU/QUvR6FBj8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T05:40:28Z"
    mac: ENC[AES256_GCM,data:b2+quC6mQPWFYPui+rLpEcJOgitSGCHe6F8UizFJJ8EfrlEy6/NaNWzHmhuRpF7XHZ35Kn0lcgVrYEV0e9rg9MhOzxvJoN8oFEcEGCe/vPonQtlaV5ut6LfHT4VKLws+s3RlHrC0oI5j1wO1vWKaNMYl8bzM8oNRPhFgyfjZfCo=,iv:f5zwTb2fprI3n3N5a5rbBod3ueOcduIyfHSzoGA05Sw=,tag:PkPy/pj/bOVQFSvIM5aYgw==,type:str]
    version: 3.13.3
