apiVersion: v1
kind: Secret
metadata:
    name: keycloak-zot-oidc
    namespace: keycloak
stringData:
    zot-client-secret: ENC[AES256_GCM,data:xS4VNOdCUsCFRmT1prh7pZCQQoY94FIHSLTznXeX47YrzJVkVhaGqCSvGw==,iv:ZvGKIsB89JcWb/5O1u4PNNxdpiA9oXG9UEyUpN46vwY=,tag:cbZ2r8hN3I2yYonoGfoXeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eEZRL2RTRUt0QTQ1eG0w
            d3VLMy9FVDNia0UvZ3hsd0tpOWdVaGUvRlNJCi9EUmEzelRpUDA2Q3pGTFVrMjh3
            Y3dvRUJjRzIxc1d1UU82OE00d2NPMHMKLS0tIG0yenVUNjhjQmZwbzE1T3pibTAv
            SjhuQnM5WU91T1MyMEFQMkc3Vms5SVEK7rMcpxm5LX9J51+IQgvubZOExrvuCCMv
            8dPbMXUqNz2JKP2ATi3AaG7GUqk4I++7mwMpW31Qf4AB16R77/3rvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T05:55:18Z"
    mac: ENC[AES256_GCM,data:Oku7hyooxB6aW+Yw1w6VcclpM3RBp+quhCP4j0dieDZP4l2VAy/PjLq9hNL/h6jEWCwzMYHsC3aOO+egYUboCXqcMK6cHvsQJEtG8vy5yw5lju8LxmFC7JNM6KzCN8p/fyzCQUKbSWBrgKxoZ6ElqFpQNrOH2df9vw+FreEl4j8=,iv:2gFY2r+H68uBtvSKG5IZyDe/K3gcfKRGjmrWYxgJqWA=,tag:jQcT/zJxwqx+n3NKMJaAKg==,type:str]
    version: 3.13.3
