apiVersion: v1
kind: Secret
metadata:
    name: immich-db-secret
    namespace: immich
stringData:
    db-password: ENC[AES256_GCM,data:FYDkb1vnloG5NhhW1tpcAz0nZMuEg6cI,iv:E2iQBsF0pugXNbQC/K1z6/m75W1WoBT4FhQUHVxr23w=,tag:KHcRisen4cbXigBCv2vFdA==,type:str]
    db-admin-password: ENC[AES256_GCM,data:6OL1b6yW+/d/NW4GEMVl9p9T7OkrQrT5,iv:bJuNCJuOCdwnNGbz7p2Rvbm45TKVRsWOTkPJ/FZkIoo=,tag:Tsuf+cTJToWFpV7Fsvkoww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRXViRUZsQi9ld0VrVFRR
            c1cwSEJPMkNDYlI4V21qM3hLajBoRFJGTkFJCkF1V2JmSEFpTmVQNVlvcGlsbnlX
            NThERnRBT3BTL0hZUTZUMDNHY28xRVkKLS0tIHVWSTRJdk9uMEw3U0pGWlZhYnBO
            ZlBoWmRNUHhNMGJDeEtnUVdvcWl1UkkKdyLixIFY0RwsmDAldNWAhxL3xrr1H65I
            uI6jAo/D9oBroOMxz/cdxpqZUFZNs0d2dpNwlbp+gWsuN2oMuUNBGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T10:57:41Z"
    mac: ENC[AES256_GCM,data:IU4Bb4D0DiCPNqIP3zdd69WPDLBU++YqTa2GDqPvq5CLJTQ74x8cH5Y6idwhh/8mi+7JDyE8XDe2wCOkzy4/dMTLg/kw8Q+4xYYkZj8Y7HzwPB//EMwVs8/zpYFw+ANJytuJx9wGIcogdnVdg0q3IiOxxrrIx32nbDdw1Vcisc4=,iv:3u7HccE2fJIPh4/og337oTuiiCX8J9NhjxGu5HzWQPg=,tag:saLrBuxOCxGU+xU2lj3ErA==,type:str]
    version: 3.13.3
