apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pg-owner-secret.yaml
  - recovery-object-store.yaml
  - helmrelease.yaml
  - pvcs.yaml
  - db-secret.yaml
  - oauth-config-secret.yaml
  - app-operator-rolebinding.yaml
