apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql-helmrelease.yaml
  - helmrelease.yaml
  - pvcs.yaml
  - db-secret.yaml
  - cilium-policy.yaml
  - oauth-config-secret.yaml
  - postgres-backup-cronjob.yaml
  - backup-s3-secret.yaml
  - backup-netpol.yaml
