apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - s3-secret.yaml
  - bucket-init-job.yaml
  - filer-postgres-secret.yaml
  - filer-postgres-schema.yaml
  - filer-postgres.yaml
  - filer-postgres-netpol.yaml
  - filer-postgres-backup-cronjob.yaml
  - csi-driver-helmrelease.yaml
