apiVersion: v1
kind: Secret
metadata:
    name: analytics-oauth
    namespace: analytics
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:t2sRuh6mWlZZm831w8Hyti5AO8JiAoldPNUr9xGK4a0=,iv:vnFGegoHBBtcmm/C4OyvSowqLL9aq3B3s+TdQ2qChDE=,tag:b8B7gR87RcEv7qvXeFCD9Q==,type:str]
    client-secret: ENC[AES256_GCM,data:NblQHFbyIbUlVnuGb1gh+hxJRCQZg3GeLXMFwSqa6yJzu6zm,iv:x/4dL0JOKZEQQqnAn7Kv++y6MCV4NXo6hRlbqACkyvk=,tag:beFIA9I8Oevs3jwLUWHesQ==,type:str]
sops:
    age:
        - recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbkdHVWd0NjU1RGJqRE5U
            bjRIWnZVdjdlVDVVTTN2YnlEbHhQeW5TbndvClk2Yy91OGhGWWJ4V1NRWndkZERP
            R0lwa3FRbXAvOHFyM1EvVUZZK2Z5MWcKLS0tIGJlNVltQnphZWhVSElrdWhDUnQ0
            eHErRGtJOGJXek94WVZ2MUY5NEZ1eDQK8sxprV+vwwBcpdmLb23kSM9LKy9Aovjo
            iTzs1r3+N/oLD97hgHIAHZYJGk4Iox+YpUjKQp3pUQWcuIjvozuM8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T09:03:04Z"
    mac: ENC[AES256_GCM,data:VzdtZdrn4T7vkyCOqEOTmixlvaLP/IFGahPWVYzRvo52j8x+VuadYDPClkBVEAdJfi7IcSHCJnb/G+uJUamkjchogmLSIZBAYIbRC/ayubomX9iVn1+GZLRYKRp8ZvfD1h5pTWzj9mBsylHW6r64WJX15Dhc4Ci5dHkNVNWZvSw=,iv:psdPTN4NswNVLjW+LSVue9eGuktyFK+hY9i9vY1HgHU=,tag:1B546utIThzt/JWANcAV2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
