apiVersion: v1
kind: Secret
metadata:
    name: analytics-lightdash-db
    namespace: analytics
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:SL34H4GMj+SZN2sEbdLMbQ3+fHa392z655JnSZi1tQ==,iv:3XpaOVIjCPWzFn/YnroNGap8zMk9pipCRdHd3wChGFo=,tag:JvYogqLnxGbUlDcim0r5Cw==,type:str]
    password: ENC[AES256_GCM,data:KJinQRyDkFLERjDBdlc9wE22NU30E0Wzs/+pEHv3tw==,iv:8FiREt7ZToOdqJKMh9NxdBUeSHwp0nqa3qgiVnhxnt4=,tag:ZtQUy2g3J+PHoiogtozC7g==,type:str]
sops:
    age:
        - recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOFhHVmVReGkyQ1JRTC9m
            aVVSMGxEc0R0ZHlQeEppbERSN3oyUCtxZ2owCjRacW5BYko1VGhjVyt1UU5JT3Rm
            TGFEekpWa05kdmM1MENvaVFHZEIvZUkKLS0tIDBWUC9sN3RacVNzd1d4MDdDWWtJ
            WldsTFYveHlWNWVaZHNtekt3VzZDQk0Kgv6BJMgnePt3CEU6a8EXo3D/Pjdeg1uQ
            tKAJGk6KEpN8qhjbiXrBMn/IIeyRjm5pusmyUFpqg1qNn2PXZ1+hhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T09:03:04Z"
    mac: ENC[AES256_GCM,data:3OrmXbmAjld/9yWwTFiTVN31jHXH9wnGootjUJIaVowBgcXsEZVgfeAoowbNK8z3Zw/Q+jMpu/FlyUL7g/NPeNMrMaeeCrOrI8Y9pIszfPXv09eAHufglYiPTirVPRijnUWbVWii8mEF2n1dXJj49Qb3p9m4l4pp+7x2nt7UhkA=,iv:PudCDgif0nuSNp8/6HUWO/jikvmFA5zMcPxH+TpUlfQ=,tag:ArHFkp8GEnYOdcGPePfXgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
