apiVersion: v1
kind: Secret
metadata:
    name: analytics-s3
    namespace: analytics
type: Opaque
stringData:
    admin_access_key_id: ENC[AES256_GCM,data:IsEW79o3MMYfPKHlhlgV3ZRzMp4ABsnO8Ay4mgEJ925FS7Q9BfMLmVCR,iv:cfX9FO5yHqIXmruU8mxXaKypfrxhRIY3uo504Qw8EwA=,tag:B/gXhqcLP0U9kx6yrzcY1g==,type:str]
    admin_secret_access_key: ENC[AES256_GCM,data:X9Ci1uFMbQ74kXFHr5DNM3vbKML6CUFppmnzDBz33iWdI60pEefufKkMAhc0eQ==,iv:pJbjEX93FPsCf6U/1xOQG9j7/kQFVFXjE95fEBJB4wo=,tag:VdDBXC33wPT3VWBba5RkZQ==,type:str]
sops:
    age:
        - recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdENmOG0wanQrb0xPcFdR
            YlhyQndvN1Y5NU5jWUswVDhRdFRFZ0RQZFNrCks0TXpxeGZUS1FSNXF2RnFHN1Bn
            MEZoQ042bzBMT2JLa3BKNFlnTDQ0TnMKLS0tIDRBSm1aa0NzMUQ5SjA1UEtDL0U5
            a1hNcFNvbEFWOEN4bTNob2FzYVlRVGsKyiQBwerlFcFs61r6RVzP/YiYf+9JDizL
            AS5yiT9DA/Zumh2KnLppK4/6azZHxqHaobE5ldc6UWL2yj4XhNqxDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T09:03:04Z"
    mac: ENC[AES256_GCM,data:9hyFZsT9xMEcT77HBQzAXPtkRSiOpBp4FfUT9DJBOOce3IWnPLsiHTuyRmo/vcZEllUPwwYZp2RI4PJcWHudLai1yEM+8CCKtgYwAK0GilVMuPaUi9AowL37I1UyzA1diGtg5M6vaNH/MSnGt/A0pd24uSW1kVUGdD+kxc9NsOQ=,iv:/YWQguGzj6sEIT7tTDxt4qVLMMiNnFST3p4D7gl3ZcU=,tag:rfUj0Xc5yaUlvGZfWYAlIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
