apiVersion: v1
kind: Secret
metadata:
    name: analytics-runtime
    namespace: analytics
type: Opaque
stringData:
    lakekeeper-encryption-key: ENC[AES256_GCM,data:pksI09PEuoLI9NqkPC8nAsrcdbZqqAADJldRD9bw04vDdLhTZRxlSRK+BbFgQlL3,iv:Ep4Esm87R3bpmvTSgE2/y7s57ejjbcA6fTCh9/FaM8c=,tag:F3gadEDFIlpQlEbe30j2Hw==,type:str]
    lightdash-secret: ENC[AES256_GCM,data:tMW1Pt5h+9tUmliMKwt00sa3HzwXUWlruej3iUjkf4g6n81IawbD,iv:qY96XOXa/z1BavuyonKuVKTt5UVXsm8gqZwfYHLMRwY=,tag:fdUDQdkplLe7cHZlFe8xBQ==,type:str]
    trino-internal-secret: ENC[AES256_GCM,data:YfiJlxhK9brgok8DaCOQYINDGxTAGwPE+nzd0J1pvgnl0iNpclbOymJDnQw=,iv:aYAPcrrI5hbkkyzNNGcXZkjKj/aFumUcY5mRhxrlzAs=,tag:leXbelYbKecqA6aDbfgB+A==,type:str]
sops:
    age:
        - recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMalZyNzZuZ0xjYVNIekNu
            Ri9Oc282NU9DU3FLRkdhT3YyMUE5M0x0RndFCnNVWjdpT1VFWmVndkVPekFwMlMz
            QzRUaGE1cUlENEMwTWhNdmRSN1ZUUUUKLS0tIHkrMm40aTBMZ3Z4WDhOK1VJVm44
            RUwxTDdFcmNxeWtja0tMcnVnZ2pPSVUK6yXPeaV6KAo7KMfsdEa8zvXMeyBlwCV6
            vAEsvd1PKXZ+tEaB/roA2UzBg6psnJbHgQLEJJ4OvyIgb1vQ/OPsVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T09:03:04Z"
    mac: ENC[AES256_GCM,data:dVoTXBUyhVoIZr6R8qQ63rqmIrK7gsubF5ptp5cFeXxhKKnAeDkG0lTo2KmI2GF7OyWGYx2SU0dRPA1Uj3ALgWbVs1EjTn5XHnUlmGTvmJu7vKNwhdZhiD7OmoydjWrA5alr50T87SBAk7xnJViqnUX4bhm6RPQMvzlyAsZhDcs=,iv:yzI6X4Kg8lFKdAPsek8+DM4lJd8AWInS1BuSlGVcZG8=,tag:ElZiSVs4M2upY7MuJDGAPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
