apiVersion: v1
kind: Secret
metadata:
    name: analytics-trino-client
    namespace: analytics
type: Opaque
stringData:
    dbt-password: ENC[AES256_GCM,data:46cj+8HWjve/ceNokSgyhCOkGVPlWIZK8mbNqOPFmy2rsYs=,iv:S47RicBe9CU/LaLhwKo/UVRiNy8DWSO57cQJFlld3YQ=,tag:ECbC2VqqAaH+M1YFhbr58w==,type:str]
    bi-password: ENC[AES256_GCM,data:b35wempRmNM0NzcX1FJ93/zHeh6i/JGBGfmL+cJHClzkJQ==,iv:KqgMZ8IG2F3B3MyqDQ69Dk9auIObzLu3/MN8MSIMKCs=,tag:QXeM9au/SuO3fKnRAwtbhw==,type:str]
sops:
    age:
        - recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNElSVzMvc3RpRVhYTW1E
            NXpCemRwN3ljQWszNmtiV2R2eUR4Sjg3NlRNClVMam9OSzNhTVp0VUFnQ0tFUjFQ
            VkxoejFFQ3Ntd0QwK0Uzc0ZhZWx6SUEKLS0tIEdSK01kZkVTaW1XdFRjN2hEMWxF
            STJvYzdWeGtHa3A5bS9FNXBsYmZVc0EKf4vxosIVbTNNhy5yDbjlYIMBTqmPRjSQ
            QzwAaMTSwN44ZdOlpE478LYpJezdVqIf0inHwJcKoG5iYu12eD8W9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T09:03:04Z"
    mac: ENC[AES256_GCM,data:feaFK3aYM09YVyrNXk/jv7Gj0hdwPzalL9DEoOfAi9N6bAcesHZfnuJJRB1IIFeh6mRKrU9nZg+sLhZMvWN1yrr9DFBeYozvNyH3PQtXXTQ2yrPwxleYod24z54HOfl1TTGO2EL7Xa5rvJ/xGVBQ2y8na+XLvjjKysq8IrWIYmk=,iv:WQIhSWktxExDXRdFKlKb01Mo/lH04Mi18yDaHDxMCBQ=,tag:gIUW8p1FcmT0sR16w66zow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
