apiVersion: v1
kind: Secret
metadata:
    name: analytics-trino
    namespace: analytics
type: Opaque
stringData:
    password.db: ENC[AES256_GCM,data:Ar0ly4pMesFVZ6q9ns867IHDr4FU4UA6Pm2ciKEsAxxI1w==,iv:JxurR4PejmsQ/SYGpKGDu2oRZRpRSgFK40nsxkDH+vM=,tag:jNhYuWAMaS0Wvmy6aykUBw==,type:str]
sops:
    age:
        - recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT2xTeUJpdkNPVm40c2N3
            TTNoSlZBazNhNEVGZzhGL1FWWlJPeGtjSUFFCjNQMzh1bkFRdTRBMXlzUlljSHRK
            amZCVHdacmZURHNrTDRTSWRmU3JSMkkKLS0tIFFhSkw4TDgyZ2ZCNnFZalp1dHBr
            enVqNEJHRytWSnVzNHhnVnhJdlVRYjAK5voUMPICHDXMnLPfYSjmjqGra/HP0HDI
            QhWQv6+IcVrPX2rXJQElK8eXhPdTZINI+Kc/Z78yzL7k/EnAZviC+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T09:03:04Z"
    mac: ENC[AES256_GCM,data:GJZEsKMnsPnQqDvZ/Qu8FyEsRq8+x8Hj8/OlAQwIKxJjgPcZHotdhju53MAqL/iNdWgSoiQyGFQNTe89aAbeWY2lg7DG0W/hf3ik1uyr9LfiMdNQVsRettNYxibP2hZJSqp85tni4SbOQOA1nUZW2ugS+ELIuY/f504RPN4VCYE=,iv:mrtF0/4CP7rKjdOTP5yBYzMafWNY2q3TgdHLW+qG9fI=,tag:2ha37TU7A9MCzclxWhY3Zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
