apiVersion: v1
kind: Secret
metadata:
    name: analytics-dagster-db
    namespace: analytics
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:bDqz9ZLQTEG3nnmSQAUB0gqWVLbjK+VabA8hqJOjkw==,iv:NmeJx5RsrfHKZQZqTteFCpFe2G6FklKDqmrM6xwiSKE=,tag:Wbt/cNB66Eo9jxn9Z3JpAg==,type:str]
    password: ENC[AES256_GCM,data:RpmKBuyMtlQFYZGE6H6Nn2wFYBRg3e5xQAn4M7aCvQ==,iv:Jze71YjDA9p2fhFAliHMZMVCysR/RTa2XEsiUqUNIvk=,tag:XK5VZvexGWqsyKVVIUpkyw==,type:str]
sops:
    age:
        - recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVUhvTVZJZjdXeXU5MHRn
            N0pFa0xlOWV6KytxdERQVll3R0cyVWRJNlY0CnN3WE54c2d5WWlBRU5yYWxTcCtS
            cjIzZW85N2dJNnlTbm9KMnRkcUp4YkUKLS0tIGN4WFV3TFZ2a2NKLzZTSjg4ak8y
            WnZBRUNYVFBsU3B5MFlYZ1I1OGZ1b0EK9MZOAUe0Q4X8V4m1WBMzLw/kPNN7Mf33
            LQ63A2zakznIPni6X+oyHNLCibZco5KxVfWdBQ/o6kpuuxemqzNNeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T09:03:04Z"
    mac: ENC[AES256_GCM,data:OLfm8/5IdLO0KtW1lWdCiPrjyaKDZ8P+Vo2Y86MX1TeBO2/39DwfAV+8627Oe9S+Yl6nsNUpceZU00FgZ+AIed7A9PhmmDBxGU0XQ5J7kc1h8CVGRW/xdXvPf7/R8rQm63gtcYW7KTZ9TCwur5uZgv7AWPuwHuObwn5DMi7+P7Y=,iv:CJs+tZ95ZmCWn5vgZZc3rKphkbrjnAGfkbzbMM9SSdM=,tag:r/e58gLyy6cotJijVewhqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
