apiVersion: v1
kind: Secret
metadata:
    name: schenkmatch-oidc-client-secret
    namespace: schenkmatch
stringData:
    client-secret: ENC[AES256_GCM,data:S0Q+Gus2yf/wnygiVKcdDphiiPmtV0levIR04Nk/dzPatB8HfLGE5VJwog==,iv:PArszm4qj6/sp+s3NwWh7rTOhlnoQxIS2Rm87F2OGXc=,tag:8PxNoh6hR6UwAFqREGMBWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcWFQZzEzbmQ5ZnpGZHNE
            b2dBVDU0SFdUTlhDdHROWTRGeXhabU5HSHg4ClVENzN5Um41MFppOHNoTHljTXUz
            ZXZJQUNmZlVQdFhPU205NDU2djlYb28KLS0tIHRsN3dXR01IZFUyaStMd3AxZE55
            TU9qMW53UjNEeDNoUGNiT1I2bHpLM2cK+savqS9e7vjfOW4JzGLG8ScFxsrmchlO
            Nq3uJMqauDvwybNeorwrIkkGoK1cFtyWOQT3aO7bipf47kki/qhehg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T05:39:26Z"
    mac: ENC[AES256_GCM,data:3RHHZKZRq5Rm9st3DEpFu6g05BL4O+dJF9OdCcUIwL7yvl091alzg+RLZfkgCf12krAWqQtuoXfHOzTckfp6Vtoz9OA8NGKEtZVVeR/O2R8mTrco7HFxGK7M/zU4sUFe0XyPow9rhS62Ft3lV8OTVxUru+a3mN1i1kj9HagiiTM=,iv:TvyD6kS6SUQEZlO/EBa3scTMa7PO5yacptpeBy8SY/0=,tag:EuLSxBXyQBZINT1G/ykaTg==,type:str]
    version: 3.13.3
