apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: prod-ingress
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
