apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signal-cli-data
  namespace: monitoring
  labels:
    velero.io/backup: "true"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
