apiVersion: v1
kind: Secret
metadata:
  name: flux-git-verify
  namespace: flux-system
type: Opaque
stringData:
  gitops-signing.sshpub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJYbSyQvLi0l/MJFIuaHSp4Oo/YPFUvUp5tcXSpQb4bk
