# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.edgex.security.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.secretstoresetup}}
  name: {{.Values.edgex.app.secretstoresetup}}
spec:
  ports:
  - name: "start"
    port: {{ .Values.edgex.bootstrap.port.secretstoretokensready }}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.secretstoresetup}}
  type: ClusterIP
  # Do not allocate cluster IP - point DNS directly at the Pod
  clusterIP: None
{{- end}}
