---
# Source: EdgeX/templates/edgex-support-notifications/edgex-support-notifications-service.yaml
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-support-notifications
  name: edgex-support-notifications
spec:
  ports:
  - name: "http"
    port: 59860
  selector:
    org.edgexfoundry.service: edgex-support-notifications
  type: ClusterIP
