apiVersion: v1
kind: Secret
metadata:
    name: telegram-credentials
    namespace: monitoring
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:dUbSuCaIXw+LX7z+iSLtW+jGOgtQ1kJTHh0a27Rs7O3Jf0kN7xcuSVxDXxnR1g==,iv:+iqQG/dqXVp2U3035jKzR06ODAGFiW4MlAC1jXnCrys=,tag:wDO99KOmmTMWq8IghFstXw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:hzf6Jl9UrgRvIMzgf58=,iv:7QWuyGy1sBE4OGBpUUAuZfHiTaEy6NJyOfd2bDJjbck=,tag:1fuICC6uZpK0T1PNsIxmjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWUM0QmRSZ2xzZkZ5a2pw
            QmhPanhyR0tORmp1RDlVNmY1M0h3bGJ5Tm53CmJYTjN4WGVlMmZMM0UvM2o2Mzh1
            dWw1alYwbkJWNUt0N0hZK1FMakhnSFkKLS0tIGJWbUI2U2ZMTjdZRXRXNHF5ZFE0
            dE13c3lDWGlyeVdSK0tDN3VCaTZxTHMK3ILBtN9gqF5e7mA/7HtrGLFbMjIEXHs9
            MqEpf8KzRBHwaUiNryw6AdOj+DargAfV9BL4yqHbCmZ8iyzLFj4WOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T21:03:33Z"
    mac: ENC[AES256_GCM,data:a92mOCV3zWe3i8SSuL2mg2/m7vpJLbxhK+Cgh+N3je7EIdIxPIfW50nAX8+3VWPS8j0petKkH2DHYSE/ANE6LDUrpjvZ2hGsWrZVx8h1asWsBHZWE3r/2FQFcutSduLNl01ZkD6WAfS4IzuS5f1TnCFbyPeBLR/hD5XVwkSzCFU=,iv:QN4qXtFg5r7Jegth5n/0yzzRffAXDQ4EfF6yRVFk9cA=,tag:mTWIUbE0Z5RxyKQI9B/Brg==,type:str]
    version: 3.13.3
