# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.core.data}}
  name: {{.Values.edgex.app.core.data}}
spec:
  ports:
  - name: "http"
    port: {{.Values.edgex.port.core.data}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.core.data}}
  type: {{.Values.expose.type}}
