apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - allow-cluster-internal.yaml
  - allow-dns.yaml
  - allow-velero-egress.yaml
  - allow-seaweedfs-internal.yaml
  - allow-monitoring.yaml
  - allow-talos-backup.yaml
  - allow-zot-egress.yaml
  - allow-internet-egress-https.yaml
  - allow-coredns-egress.yaml
  - allow-gateway-world-ingress.yaml
