apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - allow-dns.yaml
  - allow-velero-egress.yaml
  - allow-seaweedfs-internal.yaml
  - allow-monitoring.yaml
  - allow-talos-backup.yaml
