apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - allow-intra-namespace-egress.yaml
  - allow-intra-namespace-ingress.yaml
  - allow-cross-namespace-egress.yaml
  - allow-gateway-ingress.yaml
  - allow-monitoring-scrape-ingress.yaml
  - allow-gateway-world-ingress.yaml
  - allow-dns.yaml
  - allow-dns-ingress.yaml
  - allow-velero-egress.yaml
  - allow-seaweedfs-internal.yaml
  - allow-monitoring.yaml
  - allow-talos-backup.yaml
  - allow-zot-egress.yaml
  - allow-internet-egress-https.yaml
  - allow-coredns-egress.yaml

  - allow-gateway-egress-to-cluster.yaml
  - allow-tailscale-egress.yaml
