apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres.yaml
- tls.yaml
- lakekeeper.yaml
- trino.yaml
- lightdash.yaml
- dagster.yaml
- network.yaml
configMapGenerator:
- name: dagster-config
  namespace: analytics
  files:
  - config/dagster.yaml
  - config/workspace.yaml
generatorOptions:
  disableNameSuffixHash: true
