# Encrypt with SOPS before committing
# Token requires Zone:DNS:Edit + Zone:Zone:Read scoped to your domain only
# Create at: https://dash.cloudflare.com/profile/api-tokens
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:trTnEw4YRNIjwNsWTaHfPwzv8EY7lc/eBlOptCsVMoGDKdmc8GQguTikBxJOARkLh+gUFhU=,iv:E83S/tt2AMqQLbq4LEyXmTyoP+Hyr17R9B7yqTBLzH8=,tag:pDtNngOg5ygWudwxkHt0pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWTdycDVnTTJ4UWdMUlZN
            Q041eS80M2puRFBnMFBmM1BxMWlsdFY5d3dBCmZpMGxMQUtxOUJQMlhuMUw5ZGtv
            ZHc3K1JyZDVrRFFZcllZWXlTNzYrV00KLS0tIG9jT0NYbDNNSGdOc3o0NUhKWjdG
            Y1FCUk9RRDJiQzFGMEhaMU81c2RqdzQKbg7zNtvCMjr6CHWO3DkusUar1rcEhIHE
            LOH2mqcPCrq+2C1Gw04Mqu5BO5TwKC7Nv2fmVb2tYTWuNvFs3AjM+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T11:26:57Z"
    mac: ENC[AES256_GCM,data:O65bhhpIz0Y9MB3/W3yDM/7jL/o6xgVkI7Zw4ZFdwcsAWMXT9PEYd3105xcd9iI6DnkW4jYvUBwrKtaiELUBchzxK4v/xOMwLOjYCiwLUY+vXDDjR6zcw0Gxom30Tz4NpPzbmCH+oo4ShM/GQrWsOUiT6VcTvOLTkPu/n8fomAo=,iv:4uyPVKtojolzI6TjKMW9wNHXQ9Xb+rF+aWQu7xPipWU=,tag:l777cOqnKVM6GKq07MkU2Q==,type:str]
    version: 3.13.3
