# Encrypt with SOPS before committing
# Token requires Zone:DNS:Edit + Zone:Zone:Read scoped to your domain only
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:h5QRDJOzE58MZHRhHZyGgbAPBnO7UCA5pump7dH0BVfkjsBZjXwkar8AbpQC8y0QVm6HBuU=,iv:Zdg5czVUG0jTj6Fne+QNZGtKHzUbNqIPxfKlhrHrhGU=,tag:yKOTcrznETJGlOC/0+9c7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ1oyTktISWhiS0w4Rk12
            NzM0VHJHSlRPRDlWaWVtb3IzcjBIMml4azJvCjBjR0RjTVdaUXlJbHJEOEYzUC9J
            QTRnRlNIdFlqRUQwOXVHUmF6N2RwY3MKLS0tIFNRZHBSR1FLS3FLSUZ1M2luY25u
            V2RRQzVnUldZaUpBNjFBRks5RnV1dm8KOCCx5YIyvYHcXMpAdrIek/JVSwsuVTE4
            ZTL+/uqo+YlTsc7xDKY7FmbzB+3XG1SfA+lciCxEogBVIRWewRYYiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T18:57:19Z"
    mac: ENC[AES256_GCM,data:YIsPETjIJJU0NWINQejwjYQZlWsdiCDgztPKA1f+1lHCARE8DLJa6WT2biPG7BMprMiaMMQLHMFfkaGeP7FlX/yXvTYp9ApBNZUc/J/f/zMtgyBaN/SuyFDx5Dghj7FGmRR/mXg+4aHraHLkX9utMsjaPlXXYmQpiQ7kdxVWWvY=,iv:x+qtPdBiaJvYYQXbmY3TSvvYY16Big1iBIOMwueiDfM=,tag:0P8KLBpclUnUxWd8voEfVw==,type:str]
    version: 3.13.3
