apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../policies/restrict-image-registries.yaml
  - ../policies/require-resource-limits.yaml
  - ../policies/disallow-latest-tag.yaml
  - ../policies/require-readonly-rootfs.yaml
