# Encrypt with SOPS before committing
# Reuse the same Cloudflare token as cert-manager (Zone:DNS:Edit + Zone:Zone:Read)
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
stringData:
    api-token: ENC[AES256_GCM,data:cixUlzP6cIFDXYqO7si7ShWn0lsn0I5GkIjeeJTxKf9VCGV+pkMyxcPrsXhfIJnjLrIlEz4=,iv:bv/pho8iCNiBsixFonkKU4dDB1eZsxtUPfbC34Ix9Y8=,tag:7vOpd/I8FClR42wUZcggFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZSs2azVIanVNVlI4YnU5
            dSszSzhtdW85NzByR2NIWExGNTk1emlaVzFjCitrZlNPckxSY2ZqQnVGNHNxYWJG
            TCtMdkhCT0NZTkwvYkRTZ1NHSzBxVmcKLS0tIGx5KzNKVjR4WVZ5aGVobWhUWE1q
            TVYyTy9xb1NuZWJEVXpnTTg0dCszNjQKP0X/XcfroeDfWyLp1rtQ33Y547+93BOV
            xxE4AYhBa3NlK2wkgHKDm2twjpKdnuBIzErQ8sRy7dQdgUfdMdajjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T18:57:19Z"
    mac: ENC[AES256_GCM,data:XeH7cK77T+ZyvYLKFkq2oZ0E+ohSVnuPflO57AAwxe6Hi5UBQPe8jOR/jGr6VxC8COdCU6JLmnPsnNL4EnNKmkrbuGgH4MwAf0/a+S+NTPXDwKl7Nq0Rh4QeIQhQ9/BItx2Uttho0tswfEUbMN3JDrMd4Ge+lsCi0oNCZ4gawT8=,iv:PnSS4wh2uzizJkGBC4yJEbyUIB2MimfAyJzuiwqFUWA=,tag:qCregEI3zfH4xrSg4pQZVw==,type:str]
    version: 3.13.3
