# Encrypt with SOPS before committing
# Reuse the same Cloudflare token as cert-manager (Zone:DNS:Edit + Zone:Zone:Read)
# Create at: https://dash.cloudflare.com/profile/api-tokens
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
stringData:
    api-token: ENC[AES256_GCM,data:OZlzXxzJkg+0ryq9E86dlFEt/qTq4GFFpyp3ekSq8lhj83QdLz64WQ3HC1UFzsCmqGb+XPY=,iv:OMqoiLOYYxAeOgy0JgE33Yb9y/xiCnC/AG+ivoq6JCA=,tag:+COMyD8LfAzjVK7bO/fHgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkT1BQUW84djZ4Q281c0pv
            dFFZUXhVbUZJMTVHcXFUT0E0YWR6YW9Bb1RZCjJ4MmcyeXN1SlNjU05aSWNKSmdS
            bjVTU25xNXViTURMMDFOVGZXUHY2RGsKLS0tIGE1RUtSdjcvSW1YVjRZVnRuTlB4
            YVptMVJXRENraXlxYW1maE0xQTFQTVkKvaXCYxIkijMf0nS+Wq5FoaBq3QUqSnM2
            fYozOtK75d8Lz50A0a4nrRWtYPmPq3pcBlTM9oFhMDzh1wJLWjJhpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T11:26:57Z"
    mac: ENC[AES256_GCM,data:I4e3g23f+3F9RSzvShFxN9Ol0lZpu3PrgT4wqVaDlIhFpKTruUqcxk9RuqAXx8cqber/1jBw5k5KJZz9Mkuww/9PR6+12Ebt3VpV5l9n73XPrYS3s+4QLk2TEoDyGO1ykuymYqz+Y70GX/u4dUU/xdFW3NV6DakvUmGS9y0vuu8=,iv:eOroqpml/VcnbEcm42+NHoM7w/0dsKb3hhzqBHTG4jU=,tag:WQOromIN3pOmtzaj/6KSKA==,type:str]
    version: 3.13.3
