---
# Source: EdgeX/templates/edgex-ekuiper/edgex-ekuiper-service.yaml
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-kuiper
  name: edgex-kuiper
spec:
  ports:
  - name: "http"
    port: 59720
  selector:
    org.edgexfoundry.service: edgex-kuiper
  type: ClusterIP
