---
# Source: EdgeX/templates/edgex-appservice-rules/edgex-app-rules-engine-service.yaml
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-app-rules-engine
  name: edgex-app-rules-engine
spec:
  ports:
  - name: "http"
    port: 59701
  selector:
    org.edgexfoundry.service: edgex-app-rules-engine
  type: ClusterIP
