apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres.yaml
- route.yaml
- securitypolicy.yaml
- oidc-secret-referencegrant.yaml
- networkpolicy.yaml
- monitoring-egress.yaml
- alerts.yaml
