apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: otel-screener-scrape
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-gateway
  egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: real-estate-screener
        app: screener-web
    toPorts:
    - ports:
      - port: '3000'
        protocol: TCP
