apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-screener-oidc-secret
  namespace: keycloak
spec:
  from:
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: real-estate-screener
  to:
  - group: ''
    kind: Secret
    name: keycloak-edge-oidc
