---
# Source: sealed-secrets/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sealed-secrets-controller-central
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-2.6.1
    app.kubernetes.io/instance: sealed-secrets-controller-central
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: v0.18.2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-unsealer
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: sealedsecrets-serviceaccount
    namespace: toBeReplaced
