---
# Source: sealed-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-controller-central-key-admin
  namespace: toBeReplaced
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-2.6.1
    app.kubernetes.io/instance: sealed-secrets-controller-central
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: v0.18.2
rules:
  - apiGroups:
      - ""
    resourceNames:
      - sealed-secrets-key
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
---
# Source: sealed-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-controller-central-service-proxier
  namespace: toBeReplaced
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-2.6.1
    app.kubernetes.io/instance: sealed-secrets-controller-central
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: v0.18.2
rules:
  - apiGroups:
      - ""
    resourceNames:
      - sealed-secrets-controller-central
    resources:
      - services
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - 'http:sealed-secrets-controller-central:'
      - 'http:sealed-secrets-controller-central:http'
      - sealed-secrets-controller-central
    resources:
      - services/proxy
    verbs:
      - create
      - get
