---
# Source: sealed-secrets/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealedsecrets-serviceaccount
  namespace: toBeReplaced
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-2.6.1
    app.kubernetes.io/instance: sealed-secrets-controller-central
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: v0.18.2
