# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.edgex.security.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.vault}}
  name: {{.Values.edgex.app.vault}}
spec:
  replicas: {{.Values.edgex.replicas.vault}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.vault}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.vault}}
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: prep-volumes
        image: busybox:latest
        command: [ "sh", "-c", "chown -Rh 100:1000 /vault; exit 0" ]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /vault/config
            name: vault-config-tmp
          - mountPath: /vault/file
            name: vault-file
          - mountPath: /vault/logs
            name: vault-logs
      containers:
      - name: {{.Values.edgex.app.vault}}
        image: {{.Values.edgex.image.vault.repository}}:{{.Values.edgex.image.vault.tag}}
        imagePullPolicy: {{.Values.edgex.image.vault.pullPolicy}}
        command: [ "/edgex-init/vault_wait_install.sh" ]
        args: [ "server" ]
        ports:
        - containerPort: 8200
      {{- if not .Values.edgex.security.enabled }}
          hostPort: 8200
          hostIP: 0.0.0.0
      {{- end}}
        env:
        - name: VAULT_ADDR
          value: http://edgex-vault:8200
        - name: VAULT_API_ADDR
          value: http://edgex-vault:8200
        - name: VAULT_CONFIG_DIR
          value: /vault/config
        - name: VAULT_UI
          value: "true"
        - name: SKIP_CHOWN
          value: "true"
        - name: SKIP_SETCAP
          value: "true"
        - name: VAULT_DISABLE_MLOCK
          value: "true"
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /edgex-init
            name: edgex-init
          - mountPath: /vault/config
            name: vault-config-tmp
          - mountPath: /vault/file
            name: vault-file
          - mountPath: /vault/logs
            name: vault-logs   
      {{- if .Values.edgex.resources.vault.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.vault.limits.memory }}
            cpu: {{ .Values.edgex.resources.vault.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.vault.requests.memory }}
            cpu: {{ .Values.edgex.resources.vault.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.vault}}
      restartPolicy: Always
      securityContext:
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: edgex-init
          persistentVolumeClaim:
            claimName: edgex-init
        - name: vault-file
          persistentVolumeClaim:
            claimName: vault-file
        - name: vault-logs
          persistentVolumeClaim:
            claimName: vault-logs
        - name: vault-config-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
{{- end}}
