# Encrypt with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:tSrXsKw=,iv:y8yEG35nq9+aJUfZj3D88fzhSOrapTLRwbUiCZJ6vpg=,tag:NAZ6I8/VIWTICeB0UtS6gw==,type:str]
    admin-password: ENC[AES256_GCM,data:XIxFC4mMwTaNKz8=,iv:7agtVf3oa/rj4tDyzJRWeYtHEcRjBRgmDH+FV/MgCR8=,tag:ES1VrwBsHAJO74DmMQumhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZTRZR3Y5S1FmeFJTTTVp
            YVo0dkNDME16cEpkdzFFL1djcElKbUNGRVdvCjN0dmJmb1JWd3pWNm1TRFVlTFl5
            cFlESTQvaGJ5Q0QrWm5UanhiUFh3V0UKLS0tIEhZZGExQXFsK0N1UnArdWFlajJE
            UW5mcjUyVng4QkYySENuZDcvSWdXb0UKmT5wGGVHAXz3L52A/r86NYTPksDDruUp
            HKQP6sGdk459A3oZialC+muCUDCxNqZzlHW+I5bzRunyaZeihIFtMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T18:57:19Z"
    mac: ENC[AES256_GCM,data:5P+ftDLGwuEADiwvaiHHWJ2XdWfRvmo0pIUq4PC4rhMTj1qIzkkljyDiUPq7r5KWGWRm1Y3huE6fMMp95LB65EdWYAZYFmRLjL8ueY6PYfpzWTcv/UqRiSxB4poXODBVN/1MAoBw9p6qVFJQaHFJbkyglV1Xyct4IheKgbIg5UM=,iv:y5WCDB8z1/REjtcbs0LVbqdmS51dQeSOAFPyG4gZAT0=,tag:xPVf1S48OWhmDtLZvSRumA==,type:str]
    version: 3.13.3
