apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:PEoK8GfJhsibUe/zKa4PQQsO/9ilbRT1Ee4tP+qNoPI=,iv:dNLNZqKal8mhTEdO1Wb46vqedW4G8/j+1oDSVL2V4y8=,tag:ImPG9vMQMOl4Jhnwp2lUkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTytCVURWc3hSSUdnMVZh
            WW96a215OExwbDNScXQ5akovMHQxVVo0YlRrCnhja1FUVG1pZzBBRk9XeUZ3ekNE
            N2JyV28zYkRIRm5wNWlHYUpWZ0ZRaTAKLS0tIENXNUVtd0hoQVJkM1RYZFR0QVlZ
            ZTFpR0pMbUJjSTV0aGRLSXh6R2NIUlUK/GiVORCdEKXt3G42usjUGRYaNzeXyitW
            9YWr6mN93VRLRX95OYX9DdDmE477ZrIHeFke5Q5xbolQeGEno7+QMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T20:21:37Z"
    mac: ENC[AES256_GCM,data:SpRpxUrlBWRO7BonvOC72F2XFhJZTtOQitJko5pDTlUJG+nL7YueGLz3tSOu9TPaG2svAyOruzEfjGN2DTPtJ5axiMRXUeoK1sMzhQbjnSf9EreZUzgOsSz47yyX0r2hVzZqUPHs+M9NBWiKiKt/Vcs5ASCJAEfzI10uoBTkd7c=,iv:4zF2x4V6IatSm1FYZOU8jDMXErYSFc4S+6zL4jPcEQ8=,tag:/PxcRCoblv3uMOGASdnFJA==,type:str]
    version: 3.13.3
