apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7KBzPg4uXyL8GqmxUAzQF0ArydlCGLwYzw9fobFY81MmEVqX8Y9Bh4/pCg==,iv:ih8IYn2TJe1cZURe4512oK679dlnTi+FP4uVQ/QaB9E=,tag:5l7fyRYmCgVGDeEobN1rWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRS9Nbzk5S25iQVFVQU1v
            R0pvTzlxN0UzN04yOElEaGl0RHhMSUxkWmhFCnkyV2xiMSt1dGprKzVTMHNIbUk1
            L1ZZeDZoT3RrZjBObVBJMEh2TEI0T2cKLS0tIFl6MEhUWXlQdkgvUHlPZXBmamcx
            eTQxcTdCU2YyM1I5c3BTWmtmWk1QME0Kt+qq/8F1bwJ+C2zUg9V/NM+B7C6XXtR9
            7oxB3/0Dza1DJCp3Mna+1Ii6ePooeVHdroDzDN4DSrvrqBMnICG4Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:04:05Z"
    mac: ENC[AES256_GCM,data:0W+XpmS7C31F0I0bDDSDKFKjmzIImXBnY2xIYbGf548Bl64R+VCwk0JFChRipR3bC1HVwqO4OPBzybM6R0Vwl2foxiSsRgGwnd4xF1SUhVz1YCsy33kPR9R0YHMhoQbcD442IQAJTuPsGrJOKzTVKn6nbVm573ajbqNVDdAbhSE=,iv:9vz+KbS7vW6D/K+MSAT7smRbUXoQkwThySLZwdKyKYs=,tag:VKBjNEbm+jN/IYimpI0baA==,type:str]
    version: 3.13.3
