apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  dependsOn:
    - name: vmstack
      namespace: monitoring
  chart:
    spec:
      chart: grafana
      version: 10.5.15
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    service:
      appProtocol: kubernetes.io/http

    admin:
      existingSecret: grafana-admin
      userKey: admin-user
      passwordKey: admin-password

    persistence:
      enabled: true
      storageClassName: local-path
      size: 5Gi
      labels:
        velero.io/backup: "true"

    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - name: VictoriaLogs
            orgId: 1
          - name: VictoriaTraces
            orgId: 1
        datasources:
          - name: VictoriaMetrics
            type: prometheus
            url: http://vmsingle-vmstack-victoria-metrics-k8s-stack.monitoring.svc:8428
            access: proxy
            isDefault: true

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        node-exporter:
          gnetId: 1860
          revision: 37
          datasource: VictoriaMetrics
        cilium-hubble:
          gnetId: 16611
          revision: 1
          datasource: VictoriaMetrics
        velero:
          gnetId: 15469
          revision: 1
          datasource: VictoriaMetrics
        trivy-operator:
          gnetId: 17813
          revision: 1
          datasource: VictoriaMetrics

    initChownData:
      enabled: false

    securityContext:
      runAsNonRoot: true
      runAsUser: 472
      fsGroup: 472
      seccompProfile:
        type: RuntimeDefault

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]

    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
