# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.consul}}
  name: {{.Values.edgex.app.consul}}
spec:
  ports:
  - name: "http"
    port: {{.Values.edgex.port.consul}}
  {{- if .Values.edgex.security.enabled }}
  - name: "ready"
    port: {{.Values.edgex.bootstrap.port.registryready}}
  {{- end }}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.consul}}
  type: {{.Values.expose.type}}
