# Encrypt with SOPS before committing
# Create OAuth client at https://login.tailscale.com/admin/settings/oauth
# Required scopes: devices:write, routes:read, auth_keys:write
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:YELNLQvTcBeBAzH5Fd0xdfw=,iv:xRmJ5P/BEsLaRUoDSgZtYCgsc55fXOfomHu04K/GKfU=,tag:8uKa02G0+eVESjVfbQmemA==,type:str]
    client_secret: ENC[AES256_GCM,data:dkSZHCiCeo8r8M6gW25z8aQ3S1ddaSWW5ZcNXum75omwQ8/eswIcYy01VpxUbts69n9qXc2JIITAa1VfHabU,iv:KuN0qXe0Z3rVBlOH7ape2u4YI9D/U4S3iwJ9lzRx20M=,tag:dd3EofiTKIQV8Am7kbqadg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUUpyV01yY2ZhL01QdjFK
            LzNVcExjaVNOUjNuekFqc056cWdUOUhFVUU0CnUxYzF0eGQyRll6UjNuaVI3M253
            ZmdWWmRGVHFtNmNvVkFlT01vM2xlcGsKLS0tIFIvMDF1WE5XUUZJcTJIS25HS09Q
            dzh3QUUyR3RadmtnZzg2VnkvVXo5L2MKUJWO2OMR27I6+0zmB4sj6D1z/oT4MxQN
            PUd8x5dWLrIqYl/RK6jPoaYYTVnuU3a4txSqvkhVrWyxYmafY2mgvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T20:35:47Z"
    mac: ENC[AES256_GCM,data:l7BET/UyCJdSkI3Xo3jwqDJOEqx1sCzF09E6AUUnEEWVcY9LuqR2U2tbyc0LTsZsMXbxIgjSYcVcG7x6XGRPOTM8yuobvMAi1dtNvRk/QXHQDU9DPym0WvQUUddSMlTHD+TcJiKEzK8Qo0azVnd9ixssyWOss8aYGM6D3GtJhPs=,iv:c9FisClllZEXDbiduVXXsxxmWZ3+zVKZflOTYy9i0Ko=,tag:n3oOOv4HBFzqXWPTF/H0Gw==,type:str]
    version: 3.13.3
