apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscaled-subnet-router
  namespace: tailscale
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: tailscaled-subnet-router
              topologyKey: kubernetes.io/hostname
