apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: zot
data:
  config.json: |
    {
      "distSpecVersion": "1.1.0",
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "storageDriver": {
          "name": "s3",
          "region": "us-east-1",
          "regionEndpoint": "http://seaweedfs-s3.seaweedfs.svc:8333",
          "bucket": "zot-registry",
          "forcepathstyle": true,
          "skipverify": true
        }
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "auth": {
          "htpasswd": {
            "path": "/secret/htpasswd"
          }
        }
      },
      "log": {
        "level": "info"
      },
      "extensions": {
        "search": {
          "enable": true
        },
        "ui": {
          "enable": true
        },
        "metrics": {
          "enable": true,
          "prometheus": {
            "path": "/metrics"
          }
        }
      }
    }
