apiVersion: v1
kind: Secret
metadata:
    name: zot-htpasswd
    namespace: zot
stringData:
    htpasswd: ENC[AES256_GCM,data:BJVQEIiD0sBZ7O7uEgM+lFmigFo3fzBaHrP0AA13JuuwRdh+URo4QLt+sXY=,iv:jH6dztRHGE+mKdKdGPuNdirzO3t1YjxuA2FAEAlA5CI=,tag:AqrnABddEK3wWx+PBwohPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUnZ2TW5laGtzaGl4OFRO
            RXZVSTNJUnUrSy9hVlphV2hCaCs0N3cwalYwCmxLa2VGSDkyTzErZEpLVXkyL1E0
            UGY4WGg4TVBpUHZiSHc3cHprSkhDWEkKLS0tIDNlaWhDZE04K3o2bncxeGF5ejkz
            L09vZEdXRUd1d2VTck9sWUErVUd4cWcKWYXpqo0VPJy9Pz1xQrR6EyWzHAh4srsc
            jyEKytQrwCBSDQ7JzjziuOriIDBGyfIJgabF9L1md74Ia6pxP42cVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:33:59Z"
    mac: ENC[AES256_GCM,data:GzlhZkTfqgMyOhBY2FkP09/bpDRYAjpSpFrwvfqlKqY05MeDJCADcRTzPzpBl0Z9vlu0uNkR+vSMI9xjmfBJEw7OAw1hr+RCfSpst4ut+awpu0m8BoZa7qf1LkRXj/lkOWjX0RPvyoNnL+Md9lh6o/awKxUd0nyYFeIsNj1e5PQ=,iv:x0pC3SoM0NpSSdsXpSZvolENGaBweJ31J2qeJTPxloQ=,tag:h+WPIb6GDlbahcjk2Tl+Dg==,type:str]
    version: 3.13.3
