apiVersion: v1
kind: Secret
metadata:
    name: zot-oidc-credentials
    namespace: zot
stringData:
    oidc-credentials.json: ENC[AES256_GCM,data:dr0+txBuFVnP7ylsLhufVSBb7SgIGMxyvn4lAQFNdxgcUlThFaKXpxyBfarc3VHConioc16M3uSiEXVEmrbU/C0BUv1roS5p/PNmnRBUtTZPDNs=,iv:38m/Eop0fu4vfTf4gyGdDAr1QwqMNyw+zRtaJQCeLLc=,tag:DTMY86a0VRVCSgXRsCGE6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ3dYRm8ySCtEWEZwZ3Ev
            U3JsVmV0SkdYcTA5REgvOGVuYXZkdUpONGs0CmFwWjJ5VGZkZ0drVjk2encyKzZQ
            WDc0aGdUZUlTdDh5c21xTGt1cFd3VWcKLS0tIHFMTFZGRDVRbFFUZlNsTk5lUXlt
            M1RQbzQvc01oV0xBU3JyOHZNazlmZ1kKUuFQe50gBIMBdU40fUMcbAIR6e6m0Y21
            GuYQa+VDKuTjjsMh39W5bU9P/Xsyq+feTWgkeEfI2KFgJC//dNcNdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T06:03:20Z"
    mac: ENC[AES256_GCM,data:a44SYTYcdOilC9RZPvMWeAiRzZorngctOTyIYoioxzQB5FiPhWt1s1t6COC5bRbAveoSZ/P9XMXUe29RaCCbgoPL6Nj0XZCERoXMPXJldrXpgTK8LhvAjnsMHn4+d+6vOwPLqipQHJ1k6OBHw6CZ82PliiNaQUvWSdOR9362uSE=,iv:p6jBcKvlHl6P7jbp8071MBIWEMWgCrImbUJBuICXJuA=,tag:g2JBbpFkvopnQusoalXDHg==,type:str]
    version: 3.13.3
