apiVersion: v1
kind: Secret
metadata:
    name: zot-s3-credentials
    namespace: zot
stringData:
    access_key_id: ENC[AES256_GCM,data:0MVX5VY=,iv:W0PhibugGgLpka1piY74EUdKrAjoITTgQZJxOqNJ+f8=,tag:AiL4/loYuSkzX6AgHCeeew==,type:str]
    secret_access_key: ENC[AES256_GCM,data:goFY5a3JTqTM8Oo=,iv:NL60w8rh7Vv7Nkwb00Hp0/t0zsljTXTmisZJHPoQ5wo=,tag:dSD4fFceuEhIGnuiBlthLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TEhwS2VvYnErS2pnRHRK
            QSt2VDg0NnIvT0V0WW8vZSs5MGFIR05RVHpVCnVRd0dNdmp5T2x6Mm5tRmJJZW5Z
            a0VmWTFMSGxIZFpsckZqQWh6VG9qQWsKLS0tIDJnbnRCcTAvamdGYXd1ejBpTThq
            TFBGZ3FwVkNBSm5VYXJEZk9XNkhQWUUKxtqv0WTRZLVc0sHXZYfMb3PHbhCUOWsD
            G07oQf6tBa3SdwJWjlFJ7FirX+e4YHx+D+Jt6a9SPOxXg8KPHCBA0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T20:03:32Z"
    mac: ENC[AES256_GCM,data:Nw9VMaWMKMLQuONtxiug1JkOA94Hi2SZs9JCjakK/b+lcUH9pgSpnjLkJKS6Jj/Pn9hNwQEvkW8V1Obmg++JqnEYCAfgP99Y6cFZQK2cmbY0W4t9aaB8FxXdPh/X3kTOrISKYB/4Bdw6a1Y8J4Kf6EO2kBQjGbHCMdVd9aKhp2E=,iv:CTlkjQ2ind5piBXUOiCe7rT+7v/0fnqg3WD7UplU69c=,tag:O6+sMeRJkSY/o5Tyuh9vxg==,type:str]
    version: 3.13.3
