apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/00-bootstrap
  - ../../base/infrastructure/sources
  - ../../base/infrastructure/01-seaweedfs
  - ../../base/infrastructure/02-victoriametrics-stack
  - ../../base/infrastructure/03-otel-collector
  - ../../base/infrastructure/04-grafana
  - ../../base/infrastructure/05-cilium
  - ../../base/infrastructure/06-cert-manager
  - ../../base/infrastructure/07-velero
  - ../../base/infrastructure/08-external-dns
  - ../../base/infrastructure/09-reloader
  - ../../base/infrastructure/10-network-policies
  - ../../base/infrastructure/11-ingress-gateway
  - ../../base/infrastructure/12-zot
  - ../../base/infrastructure/13-trivy-operator
  - ../../base/infrastructure/14-tailscale-operator
  - ../../base/infrastructure/15-system-upgrade-controller
  - patches/velero-schedules-ha.yaml

patches:
  - path: patches/seaweedfs-ha.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: seaweedfs
  - path: patches/otel-gateway-2-replicas.yaml
    target:
      kind: Deployment
      name: otel-collector-gateway
  - path: patches/zot-replicas-2.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: zot
  - path: patches/trivy-concurrency-2.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: trivy-operator
  - path: patches/subnet-router-ha.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: tailscaled-subnet-router
      namespace: tailscale
