apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure/16-immich/config
  - ../../infrastructure/17-paperless-ngx/config
  - ../../infrastructure/16-immich/deferred
  - ../../infrastructure/17-paperless-ngx/deferred
