apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc-secret
    namespace: paperless
stringData:
    PAPERLESS_CLIENT_SECRET: ENC[AES256_GCM,data:ejMeXoaEcByZqkhwTJqfc036StIs1jHvxQenCyWrDek=,iv:YS7H8+KgDoUzFy1kTO0geGK81YTRGTbJXvEXt3e+dW0=,tag:NXUEC++sn82fma30YgnRZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVlRiSjYyZW5JMnJBRnB1
            ek5hMWRmaWFVRVl0eVcvNmh3ZXlPZTJEOHhNCm5WUE9mbVh3dTk0UnBQU1hvUzRp
            Z3E5MjFLUDZvUzJVb2pnbTFKWkZwS2sKLS0tIGZjNklVVzFMQU5Cdmc5eitWUHVz
            NUhrOURqTy9DaUE2OGp6WFBPYTJrRkUKkNhZmSAr01OLHrtcmPAm6nwXCTU0PZ2L
            Sykh0O+vhMyhr2hyygIZA7kjE0uwyaKiPwaXWe9H7PU9WXrXp8EdaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T07:29:06Z"
    mac: ENC[AES256_GCM,data:3PedL8oVItugLSPJt7gT4KNh/zOZKYe+dm9TNYA1PaaberygIfsJoUr0I+Xm7dHXrw+z/SSciZJzYkzfWTV+54/kwb4/KZb1KLoeMyEJKh5Kzx6d5vwrQXRLYSu9m2lmQg2mMD7u4E6nxr+PuO8z79Vx1FlFxBrq63+8Kbqs1Tg=,iv:/fasQ8wdd/2qOnpLeV+nekZm2mfetW/9cEwNA/u2w40=,tag:zMeCihuLQg4zaAoMYSsVNQ==,type:str]
    version: 3.13.3
