apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Eo9O6MsXi4Gy6btiyVyzGLoDR7NjaCaoFJrZxYnS0r6u+wmNHz6JrjlJLcxjQ5Nuams=,iv:MqXj06wHsj8uRsEFZy9EvHw5sbzlij9fOxS9PgykhGo=,tag:zghjBvJ8WEH97RR+B87X4A==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:nFd9HQi56IS7w7Ga9ZsadEdUyaU=,iv:4CPeL3X2535b2y4FHsyiUdx0ibpaZqB4yFceSIh3ax0=,tag:Vzrf/eLP63/3pIeeOJq2hQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TlpFeEIyWFFKbzBkMWUv
            ODJ5cVA0YlpDS05ma1ZSWi9VYkd6cGU1Q2tBCjBQTjJPYmI0dURUa3VjMFJDOXNW
            Y2hJM1pYQURpL1VkMHRueWNabHE1dUUKLS0tIEx1UTBJdUJIMkVSbGZZemJxdUw3
            eFZVb3AzYTZWenduTEp0TjJGOTh4SlEK9WRJZJmB+cVL4H6o1gIUkkV2fZ7ayuac
            Vf/qduUgLedbS6uN0DTAbJadzT1jF52a2tWuHJgtw2RRHPzo9kXXfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T10:57:41Z"
    mac: ENC[AES256_GCM,data:2Sus04pTC6gGnHRAp/8p9B8Dlu8LVnwRqrZE+jvj+0kKEQsLVGv24SuzR+3XLxBj159suzKJ4Pd9afbUjkKPWCKNx/ifa/mkLU0fQaubpfVoRY2LojJJiAGTgrV2zvdyxya4bUl9gmBFBvMp51jJKlA4eI71k6BFSLWbJU3hMoM=,iv:MAFGYp6KHfIlkqv7bMhQ/0SdGVHXVF/SFCgWkTZlHqI=,tag:wFLVcIMQUoYX8rPc42tMuA==,type:str]
    version: 3.13.3
