apiVersion: v1
kind: Secret
metadata:
    name: kubeopencode-oidc-client-secret
    namespace: kubeopencode-system
stringData:
    client-secret: ENC[AES256_GCM,data:WHhZjLgbwe2CH9hjk8be0BwAlopKL6DicH5jZkb3Gs1CRZkJdmhngNn5ig==,iv:6Q3x3AJ+AyOekUqnxchgptW3uGRgnYfk62/IPrgbjmI=,tag:mjmKh0vVFx2OZecrqNEA9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOGwvQlU2dkZVOWpiK3Bh
            Z2pFVnFFSitqenFvR1pIM2ZISVBLZG9XVWw0Ci9HUGgzSDcrVFRBWkF5VjhWS0Ux
            cXNFZXZlT00xSGVkc25PKzZtVGpUMzAKLS0tIFdqa2J4NVhQREF1RHpnVjlsMm8r
            T0Z0NU9yQVhKYk1DVkp6UDhyd3VqQ1EKblAc2XDZzjty2dhCm8Z6nVIymM9C4q3o
            ropYQ7cBPxCdiA4vCL512T6N9WFAf1NXnPwpFEin9xFraJgvY4PL2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T20:27:37Z"
    mac: ENC[AES256_GCM,data:i6LNCz01/hlXwscz0U21Y0dxKAb+LyCEcQduE/1nYU+2dn4Z8QVCjtSFhZIEoVElekUcY3q6n9F2cBfAIduVrIDH/bh4R3IJlHz/wY6QmuHFL/ehiiHle24uyyieADt//InUNdjLxIwGfvmgK3iMN8CLwGG4kUOnUbQyVvooGXs=,iv:DTHyU/1XSyc+ebC6avrzg/h9e82FZIpB4rcQiP8zDVo=,tag:RIbPtpsToDKsqbUiJ98JDA==,type:str]
    version: 3.13.3
