apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zot
  namespace: zot
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: gateway-system
      sectionName: https
  hostnames:
    - zot.homelab.data-harness.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExternalAuth
          externalAuth:
            backendRef:
              name: opa
              namespace: security
              port: 9191
            protocol: GRPC
            grpc: {}
      backendRefs:
        - name: zot
          port: 5000
