#!/usr/bin/env bash
# Generate the SOPS-encrypted Secret the ADR-005 relay needs, straight from the
# Terraform outputs.
#
#   ./scripts/make-relay-credential.sh
#
# The point of this script is that the relay's AWS secret key never appears in a
# terminal, a shell history, or a chat window. It goes from `terraform output`
# into a file that is encrypted before it is ever placed inside the repository.
#
# SOPS encryption needs only the age PUBLIC key, which is already committed in
# .sops.yaml, so this runs without any private key material present.
#
# Safety properties, in the order they matter:
#
#   1. Plaintext is written to a temp file OUTSIDE the working tree, with umask
#      077, and shredded on every exit path including failure. A crash between
#      write and encrypt therefore cannot leave a plaintext credential somewhere
#      `git add -A` would sweep up -- which is the failure that would matter most
#      here, since this repository is public.
#   2. The encrypted file is verified to contain ciphertext AND verified not to
#      contain the plaintext secret, before it is moved into the repo. sops
#      exiting 0 is not on its own proof that the value was encrypted.
#   3. The kustomization entry is added if missing. A Secret manifest that no
#      kustomization references builds cleanly and is never applied, so the relay
#      would fail on a missing secret while the file sits in Git looking correct.
set -euo pipefail
umask 077

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${REPO_ROOT}/bootstrap/terraform"
DEST_DIR="${REPO_ROOT}/cluster/base/infrastructure/34-backup"
DEST="${DEST_DIR}/backup-relay-credential.yaml"
AUDITOR_DEST="${DEST_DIR}/backup-auditor-credential.yaml"
KUSTOMIZATION="${DEST_DIR}/kustomization.yaml"

die() { echo "error: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing required tool: $1"; }

need terraform
need sops

[ -f "${REPO_ROOT}/.sops.yaml" ] || die "no .sops.yaml at repo root; cannot determine the age recipient"
[ -d "$TF_DIR" ] || die "no terraform directory at ${TF_DIR}"
[ -d "$DEST_DIR" ] || die "no 34-backup directory at ${DEST_DIR}"

# Plaintext lives outside the working tree for its entire short life.
#
# The filename must end in .yaml and the config must be passed explicitly. SOPS
# picks creation_rules by matching path_regex against the file path and finds
# .sops.yaml by walking up from the file's own directory -- so a bare mktemp name
# outside the repo matches no rule and sees no config. Both failures surface as
# "no matching creation rules found", which reads like a broken .sops.yaml rather
# than a bad temp path.
TMPDIR_SECURE="$(mktemp -d -t relay-cred.XXXXXX)"
TMP="${TMPDIR_SECURE}/backup-relay-credential.yaml"
cleanup() {
  if [ -f "$TMP" ]; then
    # Overwrite before unlinking where shred exists; rm alone leaves the block
    # contents readable on most filesystems.
    command -v shred >/dev/null 2>&1 && shred -u "$TMP" 2>/dev/null || rm -f "$TMP"
  fi
  [ -n "${TMPDIR_SECURE:-}" ] && rm -rf "$TMPDIR_SECURE" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

echo "reading Terraform outputs from ${TF_DIR}"
cd "$TF_DIR"

read_output() {
  local name="$1" value
  value="$(terraform output -raw "$name" 2>/dev/null)" || die \
    "terraform output '${name}' is unavailable. Has 'terraform apply' been run? (ADR-005 Tasks 5-8)"
  [ -n "$value" ] || die "terraform output '${name}' is empty"
  printf '%s' "$value"
}

ACCESS_KEY_ID="$(read_output backup_relay_access_key_id)"
SECRET_ACCESS_KEY="$(read_output backup_relay_secret_access_key)"
BUCKET="$(read_output backup_vault_bucket)"

# Cheap sanity checks. Wrong-but-plausible values here fail at 05:00 in a
# CronJob, which is a slow and unpleasant way to discover a typo.
case "$ACCESS_KEY_ID" in
  AKIA*) : ;;
  *) die "backup_relay_access_key_id does not look like an AWS access key (expected AKIA prefix)" ;;
esac
[ "${#SECRET_ACCESS_KEY}" -ge 20 ] || die "backup_relay_secret_access_key is implausibly short"

echo "  access key id: ${ACCESS_KEY_ID:0:4}************  (secret not displayed)"
echo "  bucket:        ${BUCKET}"

cat > "$TMP" <<YAML
# Credential the ADR-005 relay uses to write to the AWS vault (Task 9).
#
# GENERATED by scripts/make-relay-credential.sh from the Terraform outputs in
# bootstrap/terraform. Re-run that script after rotating the key rather than
# editing this file by hand.
#
# This identity can PutObject, GetObject and ListBucket, and nothing else. It
# holds no delete verb of any kind, no tagging permission, and no bucket
# configuration rights -- see backup-vault-iam.tf, where the absence is the
# point. A compromise here can write junk into the vault; it cannot remove or
# expire what is already there.
#
# AWS_BUCKET is carried in the secret rather than hardcoded in the CronJob so
# that the bucket name, key id and secret are rotated together as one unit. A
# manifest pointing at one bucket with credentials for another fails in a way
# that reads like a permissions problem.
apiVersion: v1
kind: Secret
metadata:
  name: backup-relay-aws-credential
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${SECRET_ACCESS_KEY}"
  AWS_BUCKET: "${BUCKET}"
YAML

echo "encrypting with SOPS"
sops --config "${REPO_ROOT}/.sops.yaml" --encrypt --in-place "$TMP" || die "sops encryption failed; plaintext discarded, nothing written to the repo"

# sops exiting 0 does not prove the values were encrypted -- a mismatched
# creation_rules path_regex silently produces a passthrough copy. Verify both
# directions: ciphertext present, and the plaintext secret absent.
grep -q 'ENC\[AES256_GCM' "$TMP" \
  || die "output contains no SOPS ciphertext; refusing to write. Check creation_rules in .sops.yaml"
if grep -qF -- "$SECRET_ACCESS_KEY" "$TMP"; then
  die "PLAINTEXT SECRET FOUND in the encrypted output; refusing to write anything to the repo"
fi
for k in AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_BUCKET; do
  grep -qE "^\s+${k}: ENC\[" "$TMP" || die "${k} was not encrypted; refusing to write"
done
echo "  verified: 3 values encrypted, plaintext absent"

install -m 0600 "$TMP" "$DEST"
chmod 0644 "$DEST"
echo "wrote ${DEST#"${REPO_ROOT}/"}"

# A manifest nothing references builds cleanly and is never applied, so the
# relay or reconciler would fail on a missing secret while the file sat in Git
# looking correct. Shell-native and self-verifying: an earlier version embedded
# python inside this heredoc, its escapes collapsed, and it failed silently
# after the credential had already been written -- producing exactly the
# unreferenced-manifest state it was meant to prevent.
add_to_kustomization() {
  f="$1"
  if grep -q "$f" "$KUSTOMIZATION"; then
    echo "kustomization already references $f"
    return 0
  fi
  awk -v new="  - $f" '
    { lines[NR] = $0; if ($0 ~ /^  - .*\.yaml$/) last = NR }
    END { for (i = 1; i <= NR; i++) { print lines[i]; if (i == last) print new } }
  ' "$KUSTOMIZATION" > "${KUSTOMIZATION}.tmp" && mv "${KUSTOMIZATION}.tmp" "$KUSTOMIZATION"
  grep -q "$f" "$KUSTOMIZATION" || die "failed to add $f to kustomization.yaml"
  echo "added $f to kustomization.yaml"
}

add_to_kustomization "backup-relay-credential.yaml"
add_to_kustomization "backup-auditor-credential.yaml"

cat <<'NEXT'

Next steps:

  1. Confirm the overlay still builds and the secret is ciphertext in the diff:
       kubectl kustomize cluster/overlays/1-node > /dev/null
       git diff --stat

  2. Commit and merge. Flux applies the secret; the relay stays suspended.

  3. Unsuspend the relay in a SEPARATE change, so the secret is already live
     when the first run fires:
       cluster/base/infrastructure/34-backup/backup-relay.yaml  ->  suspend: false

  4. Trigger one run by hand rather than waiting for 05:00, and confirm the
     objects actually arrive:
       kubectl create job -n longhorn-system relay-test --from=cronjob/backup-relay
       kubectl logs -n longhorn-system -l job-name=relay-test --tail=40

  5. Verify what AWS is enforcing, including that delete is genuinely denied:
       ./scripts/verify-backup-vault.sh
NEXT
