---
# Source: EdgeX/templates/edgex-support-scheduler/edgex-support-scheduler-service.yaml
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-support-scheduler
  name: edgex-support-scheduler
spec:
  ports:
  - name: "http"
    port: 59861
  selector:
    org.edgexfoundry.service: edgex-support-scheduler
  type: ClusterIP
