# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Default values for Edgex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

expose:
  # Option value: ClusterIP/NodePort/LoadBalancer
  type: ClusterIP

# edgex defines a set of configuration properties for application-level concerns
edgex:

  # app defines a single point in naming/referring to an application. For each application, the value
  # define its label name, resource name or base of the resource name, and service name.
  app:
    core:
      command: edgex-core-command
      data: edgex-core-data
      metadata: edgex-core-metadata
    support:
      notifications: edgex-support-notifications
      scheduler: edgex-support-scheduler
    appservice:
      rules: edgex-app-rules-engine
    device:
      virtual: edgex-device-virtual
      rest: edgex-device-rest
    ui: edgex-ui
    system: edgex-sys-mgmt-agent
    consul: edgex-core-consul
    redis: edgex-redis
    ekuiper: edgex-kuiper
    vault: edgex-vault
    bootstrapper: edgex-security-bootstrapper
    secretstoresetup: edgex-security-secretstore-setup

  # port defines configuration properties for container, target and host ports
  port:
    core:
      data: 59880
      metadata: 59881
      command: 59882
    support:
      notifications: 59860
      scheduler: 59861
    appservice:
      rules: 59701
    device:
      virtual: 59900
      rest: 59986
    system: 58890
    ui: 4000
    consul: 8500
    redis: 6379
    ekuiper: 59720

  # ports used by security bootstrapping for stage gating edgex init
  bootstrap:
    port:
      start: 54321
      readytorun: 54329
      secretstoretokensready: 54322
      databaseready: 54323
      registryready: 54324
      kongdbready: 54325

  # Duplicate default IP binding choice of docker-compose
  hostPortInternalBind: 127.0.0.1
  hostPortExternalBind: 0.0.0.0

  # replicas defines the number of replicas in a Deployment for the respective application
  replicas:
    core:
      command: 1
      data: 1
      metadata: 1
    support:
      notifications: 1
      scheduler: 1
    appservice:
      rules: 1
    device:
      virtual: 1
      rest: 1
    ui: 1
    system: 1
    consul: 1
    redis: 1
    ekuiper: 1

  # UID/GID for container user
  security:
    enabled: false
    runAsUser: 2002
    runAsGroup: 2001
    tlsHost: edgex

  storage:
    className: ""

