---
# Source: EdgeX/templates/edgex-system/edgex-sys-mgmt-agent-service.yaml
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-sys-mgmt-agent
  name: edgex-sys-mgmt-agent
spec:
  ports:
  - name: "http"
    port: 58890
  selector:
    org.edgexfoundry.service: edgex-sys-mgmt-agent
  type: ClusterIP
