# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.virtual}}
  name: {{.Values.edgex.app.device.virtual}}
spec:
  ports:
  - name: "{{.Values.edgex.port.device.virtual}}"
    port: {{.Values.edgex.port.device.virtual}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.device.virtual}}
  type: {{.Values.expose.type}}

