apiVersion: v1
kind: Secret
metadata:
    name: dex-secrets
    namespace: dex
stringData:
    grafana-client-secret: ENC[AES256_GCM,data:VMuWZu5QY6VoyU0DXn3jambZ4sHtDZRY0DR2Cn6lexlloa2WhTYb2cXQzQ==,iv:il+N6MdP25mdoWmkA0aCAveW1th25e1OEW48VhXb234=,tag:efV3Rmr5Lo1psAkFuXXbiw==,type:str]
    admin-password-hash: ENC[AES256_GCM,data:de8CkdFZajrhY5eQurANZ1fF16AxmW/R/Uo09udY8OnfKDnMM5NuPFgN10Y3uzzh/In6d+aKcPLN9AnY,iv:yx2wwS7Htirw2HsgKjWIw7XLuNG8LhsZ4As9T1W1vsQ=,tag:Hcqh7lUANEmTLhM39F61jw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NkFOeVBOdEU5YjNCZkJi
            akVkenR3b0RPVStScHo5UVFCck53YmFKdnk0Cml4K2daYUE5RVdMRVdiNmlFNEtY
            OU81akVIcE56RmM0QitWd3krSk83a3cKLS0tIFd3SEF6cDVHemh2NkluUXFoRy9V
            SGFWWHBrZktabmxWTlFQVnlSWDUyNEUKnbkTNLPzHk6jIUTd7seyIIDln/KZCMD/
            ip2PiM0r72F01x4+kYfWWM3UIXwyJOeFasTt/BciJLZ595BtztXKAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:04:05Z"
    mac: ENC[AES256_GCM,data:fqVpiscNVsT5UsNZEWEVMa7ZcrNWJGyysP1otjGKQ/QtpHrRsED+BIY6Ri+qUGsZVB0Qv589jdUhTtYnLPlGY7tROX00S9kPOmxMZ4ZfKNXSgN2hxmLB2aFCuqcmp/cnzZAUUErTMD50zGpIj+QUZldb6vNVvhQdTdYuZF5z1xY=,iv:hQ8NjFV1y7jUTK6Pu1QMsv14weZRBCOYtvuAVM43v6Y=,tag:BxlgnmIbqgsf+KIRiYFpAQ==,type:str]
    version: 3.13.3
