apiVersion: v1
kind: Secret
metadata:
    name: dex-static-clients
    namespace: dex
stringData:
    values.yaml: ENC[AES256_GCM,data:Er1UBygBjTLB0n4G+89ZNPtseZKrXb7jjlqg0NMksWaAEq3PR4R0ayi/BCymdSU0uc8JSAKR1qILYmb2EvJvkErW13+HGGntjlfQ0mDClxpKbWOrsmyTFuLN3LvIqhMWNRTsksl9Mv4oaqQS7Hbtu6dYMxALWYQxpzX5Tl/wWWXJLn5tyzWKBESH3fmAEqf9ciCaq/KFSw+0NjcgljRiezDegThinXZdjlJzumbxIV5T8zqvNxy0hedClLGCkzUtE9goAvprWXtEjrx3n00Ap0fOPa46,iv:Gri8xodlsUDiwqT/8G2d5lDqxx/he9vB3VNi0rPY08g=,tag:YNdhIiFHhSo4T/dT2ZGHZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWkhtQUFYRVVvN0ZvbUYy
            WXpLcUNsTElweWl3SzNtNFVnNW94bkRXaWlvCkF3RXYyWWk2cUdFb3NET3BUbUhI
            M2p2UUtiTTFWVDc4U3hqVmZsNGpTNm8KLS0tIGw2Q2o1bEt6cXB6b2dnMEVZdzEv
            ZU42eEFKY1d4NWhWRGZDMTBRSjNIM1EKh/WNz+jD0BF1cuagYuWwiA40w0765Qz/
            SeVy8mC2JUq3E9x9xwvr0RxHrbzEHdNC5eZ5TcvldwhLx0ppL2XpMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wgk7g6rwkm2xjq08vj66aa53rxhdxvzjldrurkukcfuacxxxj34svculzn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T20:47:28Z"
    mac: ENC[AES256_GCM,data:mWDX6qn8g20sFVd0yj7oWjBNiGIRSExPz0G7gukpza/k/d5dsUBnpNAOk+iYwvmx7hBSAtuyWFY5eaiiblypJzeJn1r9ZBChVMizmss/43naqCEuKT/I+ZLvDYOqEb6032q1FU+Z9XrWShn9Br9PDuNDusPONNmg5prmJDi5Hl8=,iv:jLg4bmIqjzl23SOqKM+oUsQD9cgKyY+GOK9PIxo4fFY=,tag:Rn/n6dDwISbwpo525J5bQQ==,type:str]
    version: 3.13.3
