---
# Source: EdgeX/templates/edgex-core-data/edgex-core-data-service.yaml
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-data
  name: edgex-core-data
spec:
  ports:
  - name: "http"
    port: 59880
  selector:
    org.edgexfoundry.service: edgex-core-data
  type: ClusterIP
