# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.edgex.security.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-kong-db
  name: edgex-kong-db
spec:
  ports:
  - name: "dummy-psql"
    port: 5432
    targetPort: 8080
  - name: "ready"
    port: {{.Values.edgex.bootstrap.port.kongdbready}}
    targetPort: 8080
  selector:
    org.edgexfoundry.service: edgex-kong-db
  type: ClusterIP
{{- end }}
